package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class AppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.bus_type
     *
     * @mbggenerated
     */
    private String busType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.app_type
     *
     * @mbggenerated
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.call_no
     *
     * @mbggenerated
     */
    private String callNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.callback_url
     *
     * @mbggenerated
     */
    private String callbackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.associate_type
     *
     * @mbggenerated
     */
    private String associateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.url_status
     *
     * @mbggenerated
     */
    private String urlStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /** 限额消费 */
    private BigDecimal quota;
    private String limitFlag;//是否限额。00：关闭     01：开启'
    private String isDefined;//系统默认或自定义中继(0:系统默认,1:自定义)

    /** 业务是否试用专用路由 */
    private String isRoute;
    /** 专用路由编码 */
    private String routeCode;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.id
     *
     * @return the value of tb_app_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.id
     *
     * @param id the value for tb_app_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.appid
     *
     * @return the value of tb_app_info.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.appid
     *
     * @param appid the value for tb_app_info.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.sid
     *
     * @return the value of tb_app_info.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.sid
     *
     * @param sid the value for tb_app_info.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.bus_type
     *
     * @return the value of tb_app_info.bus_type
     *
     * @mbggenerated
     */
    public String getBusType() {
        return busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.bus_type
     *
     * @param busType the value for tb_app_info.bus_type
     *
     * @mbggenerated
     */
    public void setBusType(String busType) {
        this.busType = busType == null ? null : busType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.app_name
     *
     * @return the value of tb_app_info.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.app_name
     *
     * @param appName the value for tb_app_info.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.app_type
     *
     * @return the value of tb_app_info.app_type
     *
     * @mbggenerated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.app_type
     *
     * @param appType the value for tb_app_info.app_type
     *
     * @mbggenerated
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.call_no
     *
     * @return the value of tb_app_info.call_no
     *
     * @mbggenerated
     */
    public String getCallNo() {
        return callNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.call_no
     *
     * @param callNo the value for tb_app_info.call_no
     *
     * @mbggenerated
     */
    public void setCallNo(String callNo) {
        this.callNo = callNo == null ? null : callNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.callback_url
     *
     * @return the value of tb_app_info.callback_url
     *
     * @mbggenerated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.callback_url
     *
     * @param callbackUrl the value for tb_app_info.callback_url
     *
     * @mbggenerated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.associate_type
     *
     * @return the value of tb_app_info.associate_type
     *
     * @mbggenerated
     */
    public String getAssociateType() {
        return associateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.associate_type
     *
     * @param associateType the value for tb_app_info.associate_type
     *
     * @mbggenerated
     */
    public void setAssociateType(String associateType) {
        this.associateType = associateType == null ? null : associateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.url_status
     *
     * @return the value of tb_app_info.url_status
     *
     * @mbggenerated
     */
    public String getUrlStatus() {
        return urlStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.url_status
     *
     * @param urlStatus the value for tb_app_info.url_status
     *
     * @mbggenerated
     */
    public void setUrlStatus(String urlStatus) {
        this.urlStatus = urlStatus == null ? null : urlStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.status
     *
     * @return the value of tb_app_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.status
     *
     * @param status the value for tb_app_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.create_date
     *
     * @return the value of tb_app_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.create_date
     *
     * @param createDate the value for tb_app_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info.update_date
     *
     * @return the value of tb_app_info.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info.update_date
     *
     * @param updateDate the value for tb_app_info.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public BigDecimal getQuota() {
        return quota;
    }

    public void setQuota(BigDecimal quota) {
        this.quota = quota;
    }

    public String getLimitFlag() {
        return limitFlag;
    }

    public void setLimitFlag(String limitFlag) {
        this.limitFlag = limitFlag;
    }

    public String getIsDefined() {
        return isDefined;
    }

    public void setIsDefined(String isDefined) {
        this.isDefined = isDefined;
    }

    public String getIsRoute() {
        return isRoute;
    }

    public void setIsRoute(String isRoute) {
        this.isRoute = isRoute;
    }

    public String getRouteCode() {
        return routeCode;
    }

    public void setRouteCode(String routeCode) {
        this.routeCode = routeCode;
    }

}