package com.e9cloud.mybatis.domain;

public class AppointLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.xh_telno
     *
     * @mbggenerated
     */
    private String xhTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.dest_telno
     *
     * @mbggenerated
     */
    private String destTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.rn
     *
     * @mbggenerated
     */
    private String rn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appoint_link.remake
     *
     * @mbggenerated
     */
    private String remake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.id
     *
     * @return the value of tb_appoint_link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.id
     *
     * @param id the value for tb_appoint_link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.xh_telno
     *
     * @return the value of tb_appoint_link.xh_telno
     *
     * @mbggenerated
     */
    public String getXhTelno() {
        return xhTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.xh_telno
     *
     * @param xhTelno the value for tb_appoint_link.xh_telno
     *
     * @mbggenerated
     */
    public void setXhTelno(String xhTelno) {
        this.xhTelno = xhTelno == null ? null : xhTelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.dest_telno
     *
     * @return the value of tb_appoint_link.dest_telno
     *
     * @mbggenerated
     */
    public String getDestTelno() {
        return destTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.dest_telno
     *
     * @param destTelno the value for tb_appoint_link.dest_telno
     *
     * @mbggenerated
     */
    public void setDestTelno(String destTelno) {
        this.destTelno = destTelno == null ? null : destTelno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.type
     *
     * @return the value of tb_appoint_link.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.type
     *
     * @param type the value for tb_appoint_link.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.rn
     *
     * @return the value of tb_appoint_link.rn
     *
     * @mbggenerated
     */
    public String getRn() {
        return rn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.rn
     *
     * @param rn the value for tb_appoint_link.rn
     *
     * @mbggenerated
     */
    public void setRn(String rn) {
        this.rn = rn == null ? null : rn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appoint_link.remake
     *
     * @return the value of tb_appoint_link.remake
     *
     * @mbggenerated
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appoint_link.remake
     *
     * @param remake the value for tb_appoint_link.remake
     *
     * @mbggenerated
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }
}