package com.e9cloud.mybatis.domain;

public class AreacodePcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areacode_pcode.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areacode_pcode.pcode_name
     *
     * @mbggenerated
     */
    private String pcodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areacode_pcode.pcode
     *
     * @mbggenerated
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areacode_pcode.areacode_name
     *
     * @mbggenerated
     */
    private String areacodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areacode_pcode.areacode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areacode_pcode.id
     *
     * @return the value of areacode_pcode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areacode_pcode.id
     *
     * @param id the value for areacode_pcode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areacode_pcode.pcode_name
     *
     * @return the value of areacode_pcode.pcode_name
     *
     * @mbggenerated
     */
    public String getPcodeName() {
        return pcodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areacode_pcode.pcode_name
     *
     * @param pcodeName the value for areacode_pcode.pcode_name
     *
     * @mbggenerated
     */
    public void setPcodeName(String pcodeName) {
        this.pcodeName = pcodeName == null ? null : pcodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areacode_pcode.pcode
     *
     * @return the value of areacode_pcode.pcode
     *
     * @mbggenerated
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areacode_pcode.pcode
     *
     * @param pcode the value for areacode_pcode.pcode
     *
     * @mbggenerated
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areacode_pcode.areacode_name
     *
     * @return the value of areacode_pcode.areacode_name
     *
     * @mbggenerated
     */
    public String getAreacodeName() {
        return areacodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areacode_pcode.areacode_name
     *
     * @param areacodeName the value for areacode_pcode.areacode_name
     *
     * @mbggenerated
     */
    public void setAreacodeName(String areacodeName) {
        this.areacodeName = areacodeName == null ? null : areacodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areacode_pcode.areacode
     *
     * @return the value of areacode_pcode.areacode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areacode_pcode.areacode
     *
     * @param areacode the value for areacode_pcode.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }
}