package com.e9cloud.mybatis.domain;

import java.util.Date;

public class MaskNumRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.arean
     *
     * @mbggenerated
     */
    private String arean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.phonea
     *
     * @mbggenerated
     */
    private String phonea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.phoneb
     *
     * @mbggenerated
     */
    private String phoneb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.need_record
     *
     * @mbggenerated
     */
    private String needRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.make_num
     *
     * @mbggenerated
     */
    private String makeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.second
     *
     * @mbggenerated
     */
    private String second;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.time_out
     *
     * @mbggenerated
     */
    private Date timeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mask_num_relation.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.id
     *
     * @return the value of tb_mask_num_relation.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.id
     *
     * @param id the value for tb_mask_num_relation.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.appid
     *
     * @return the value of tb_mask_num_relation.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.appid
     *
     * @param appid the value for tb_mask_num_relation.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.arean
     *
     * @return the value of tb_mask_num_relation.arean
     *
     * @mbggenerated
     */
    public String getArean() {
        return arean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.arean
     *
     * @param arean the value for tb_mask_num_relation.arean
     *
     * @mbggenerated
     */
    public void setArean(String arean) {
        this.arean = arean == null ? null : arean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.phonea
     *
     * @return the value of tb_mask_num_relation.phonea
     *
     * @mbggenerated
     */
    public String getPhonea() {
        return phonea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.phonea
     *
     * @param phonea the value for tb_mask_num_relation.phonea
     *
     * @mbggenerated
     */
    public void setPhonea(String phonea) {
        this.phonea = phonea == null ? null : phonea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.phoneb
     *
     * @return the value of tb_mask_num_relation.phoneb
     *
     * @mbggenerated
     */
    public String getPhoneb() {
        return phoneb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.phoneb
     *
     * @param phoneb the value for tb_mask_num_relation.phoneb
     *
     * @mbggenerated
     */
    public void setPhoneb(String phoneb) {
        this.phoneb = phoneb == null ? null : phoneb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.need_record
     *
     * @return the value of tb_mask_num_relation.need_record
     *
     * @mbggenerated
     */
    public String getNeedRecord() {
        return needRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.need_record
     *
     * @param needRecord the value for tb_mask_num_relation.need_record
     *
     * @mbggenerated
     */
    public void setNeedRecord(String needRecord) {
        this.needRecord = needRecord == null ? null : needRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.make_num
     *
     * @return the value of tb_mask_num_relation.make_num
     *
     * @mbggenerated
     */
    public String getMakeNum() {
        return makeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.make_num
     *
     * @param makeNum the value for tb_mask_num_relation.make_num
     *
     * @mbggenerated
     */
    public void setMakeNum(String makeNum) {
        this.makeNum = makeNum == null ? null : makeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.second
     *
     * @return the value of tb_mask_num_relation.second
     *
     * @mbggenerated
     */
    public String getSecond() {
        return second;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.second
     *
     * @param second the value for tb_mask_num_relation.second
     *
     * @mbggenerated
     */
    public void setSecond(String second) {
        this.second = second == null ? null : second.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.time_out
     *
     * @return the value of tb_mask_num_relation.time_out
     *
     * @mbggenerated
     */
    public Date getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.time_out
     *
     * @param timeOut the value for tb_mask_num_relation.time_out
     *
     * @mbggenerated
     */
    public void setTimeOut(Date timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mask_num_relation.create_date
     *
     * @return the value of tb_mask_num_relation.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mask_num_relation.create_date
     *
     * @param createDate the value for tb_mask_num_relation.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}