package com.e9cloud.mybatis.domain;

public class TelnoInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.telno
     *
     * @mbggenerated
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.pcode
     *
     * @mbggenerated
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.ccode
     *
     * @mbggenerated
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.areacode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telno_info.card
     *
     * @mbggenerated
     */
    private String card;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.Id
     *
     * @return the value of telno_info.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.Id
     *
     * @param id the value for telno_info.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.telno
     *
     * @return the value of telno_info.telno
     *
     * @mbggenerated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.telno
     *
     * @param telno the value for telno_info.telno
     *
     * @mbggenerated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.pcode
     *
     * @return the value of telno_info.pcode
     *
     * @mbggenerated
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.pcode
     *
     * @param pcode the value for telno_info.pcode
     *
     * @mbggenerated
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.pname
     *
     * @return the value of telno_info.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.pname
     *
     * @param pname the value for telno_info.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.ccode
     *
     * @return the value of telno_info.ccode
     *
     * @mbggenerated
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.ccode
     *
     * @param ccode the value for telno_info.ccode
     *
     * @mbggenerated
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.cname
     *
     * @return the value of telno_info.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.cname
     *
     * @param cname the value for telno_info.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.areacode
     *
     * @return the value of telno_info.areacode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.areacode
     *
     * @param areacode the value for telno_info.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.operator
     *
     * @return the value of telno_info.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.operator
     *
     * @param operator the value for telno_info.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telno_info.card
     *
     * @return the value of telno_info.card
     *
     * @mbggenerated
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telno_info.card
     *
     * @param card the value for telno_info.card
     *
     * @mbggenerated
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }
}