package com.e9cloud.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 用户基本信息
 */
public class User implements Serializable {

    private static final long serialVersionUID = -5871590343444898544L;

    /** 用户主账号 */
    private String uid;

    /** 应用主账号 */
    private String sid;

    /** 计费主账号 */
    private String feeid;

    /** 账户余额 */
    private BigDecimal fee;

    /** 验签标识 */
    private String token;

    /** 邮箱 */
    private String email;

    /** 手机号 */
    private String mobile;

    /** 用户类型 */
    private String utype;

    /** 用户昵称 */
    private String nick;

    /** 用户姓名 */
    private String name;

    /** 用户状态 */
    private String status;

    /** 用户创建日期 */
    private Date createDate;

    /** 用户更新日期 */
    private Date updateDate;

    /** 最后一次登录时间 */
    private Date loginDate;

    /** 登录次数 */
    private Integer loginCount;

    private UserPerson userPerson;
    private UserCompany userCompany;
    private UserExternInfo userExternInfo;

    public UserPerson getUserPerson() {
        return userPerson;
    }

    public void setUserPerson(UserPerson userPerson) {
        this.userPerson = userPerson;
    }

    public UserCompany getUserCompany() {
        return userCompany;
    }

    public void setUserCompany(UserCompany userCompany) {
        this.userCompany = userCompany;
    }

    public UserExternInfo getUserExternInfo() {
        return userExternInfo;
    }

    public void setUserExternInfo(UserExternInfo userExternInfo) {
        this.userExternInfo = userExternInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.uid
     *
     * @return the value of tb_user_admin.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.uid
     *
     * @param uid the value for tb_user_admin.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.email
     *
     * @return the value of tb_user_admin.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.email
     *
     * @param email the value for tb_user_admin.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.mobile
     *
     * @return the value of tb_user_admin.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.mobile
     *
     * @param mobile the value for tb_user_admin.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.utype
     *
     * @return the value of tb_user_admin.utype
     *
     * @mbggenerated
     */
    public String getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.utype
     *
     * @param utype the value for tb_user_admin.utype
     *
     * @mbggenerated
     */
    public void setUtype(String utype) {
        this.utype = utype == null ? null : utype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.nick
     *
     * @return the value of tb_user_admin.nick
     *
     * @mbggenerated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.nick
     *
     * @param nick the value for tb_user_admin.nick
     *
     * @mbggenerated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.name
     *
     * @return the value of tb_user_admin.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.name
     *
     * @param name the value for tb_user_admin.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.status
     *
     * @return the value of tb_user_admin.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.status
     *
     * @param status the value for tb_user_admin.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.create_date
     *
     * @return the value of tb_user_admin.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.create_date
     *
     * @param createDate the value for tb_user_admin.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.update_date
     *
     * @return the value of tb_user_admin.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.update_date
     *
     * @param updateDate the value for tb_user_admin.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.login_date
     *
     * @return the value of tb_user_admin.login_date
     *
     * @mbggenerated
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.login_date
     *
     * @param loginDate the value for tb_user_admin.login_date
     *
     * @mbggenerated
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.login_count
     *
     * @return the value of tb_user_admin.login_count
     *
     * @mbggenerated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.login_count
     *
     * @param loginCount the value for tb_user_admin.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.sid
     *
     * @param sid the value for tb_user_admin.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.feeid
     *
     * @return the value of tb_user_admin.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.feeid
     *
     * @param feeid the value for tb_user_admin.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.fee
     *
     * @return the value of tb_user_admin.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.fee
     *
     * @param fee the value for tb_user_admin.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin.token
     *
     * @return the value of tb_user_admin.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin.token
     *
     * @param token the value for tb_user_admin.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}