package com.e9cloud.mybatis.domain;

import java.util.Date;

public class UserCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.legal_representative
     *
     * @mbggenerated
     */
    private String legalRepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.telno
     *
     * @mbggenerated
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.website
     *
     * @mbggenerated
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.trade_id
     *
     * @mbggenerated
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.organization_no
     *
     * @mbggenerated
     */
    private String organizationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.organization_pic
     *
     * @mbggenerated
     */
    private String organizationPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.tax_reg_no
     *
     * @mbggenerated
     */
    private String taxRegNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.tax_reg_pic
     *
     * @mbggenerated
     */
    private String taxRegPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.business_license_no
     *
     * @mbggenerated
     */
    private String businessLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.business_license_pic
     *
     * @mbggenerated
     */
    private String businessLicensePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_authen_company.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.id
     *
     * @return the value of tb_user_admin_authen_company.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.id
     *
     * @param id the value for tb_user_admin_authen_company.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.uid
     *
     * @return the value of tb_user_admin_authen_company.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.uid
     *
     * @param uid the value for tb_user_admin_authen_company.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.name
     *
     * @return the value of tb_user_admin_authen_company.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.name
     *
     * @param name the value for tb_user_admin_authen_company.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.legal_representative
     *
     * @return the value of tb_user_admin_authen_company.legal_representative
     *
     * @mbggenerated
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.legal_representative
     *
     * @param legalRepresentative the value for tb_user_admin_authen_company.legal_representative
     *
     * @mbggenerated
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative == null ? null : legalRepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.telno
     *
     * @return the value of tb_user_admin_authen_company.telno
     *
     * @mbggenerated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.telno
     *
     * @param telno the value for tb_user_admin_authen_company.telno
     *
     * @mbggenerated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.address
     *
     * @return the value of tb_user_admin_authen_company.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.address
     *
     * @param address the value for tb_user_admin_authen_company.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.website
     *
     * @return the value of tb_user_admin_authen_company.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.website
     *
     * @param website the value for tb_user_admin_authen_company.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.trade_id
     *
     * @return the value of tb_user_admin_authen_company.trade_id
     *
     * @mbggenerated
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.trade_id
     *
     * @param tradeId the value for tb_user_admin_authen_company.trade_id
     *
     * @mbggenerated
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.organization_no
     *
     * @return the value of tb_user_admin_authen_company.organization_no
     *
     * @mbggenerated
     */
    public String getOrganizationNo() {
        return organizationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.organization_no
     *
     * @param organizationNo the value for tb_user_admin_authen_company.organization_no
     *
     * @mbggenerated
     */
    public void setOrganizationNo(String organizationNo) {
        this.organizationNo = organizationNo == null ? null : organizationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.organization_pic
     *
     * @return the value of tb_user_admin_authen_company.organization_pic
     *
     * @mbggenerated
     */
    public String getOrganizationPic() {
        return organizationPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.organization_pic
     *
     * @param organizationPic the value for tb_user_admin_authen_company.organization_pic
     *
     * @mbggenerated
     */
    public void setOrganizationPic(String organizationPic) {
        this.organizationPic = organizationPic == null ? null : organizationPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.tax_reg_no
     *
     * @return the value of tb_user_admin_authen_company.tax_reg_no
     *
     * @mbggenerated
     */
    public String getTaxRegNo() {
        return taxRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.tax_reg_no
     *
     * @param taxRegNo the value for tb_user_admin_authen_company.tax_reg_no
     *
     * @mbggenerated
     */
    public void setTaxRegNo(String taxRegNo) {
        this.taxRegNo = taxRegNo == null ? null : taxRegNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.tax_reg_pic
     *
     * @return the value of tb_user_admin_authen_company.tax_reg_pic
     *
     * @mbggenerated
     */
    public String getTaxRegPic() {
        return taxRegPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.tax_reg_pic
     *
     * @param taxRegPic the value for tb_user_admin_authen_company.tax_reg_pic
     *
     * @mbggenerated
     */
    public void setTaxRegPic(String taxRegPic) {
        this.taxRegPic = taxRegPic == null ? null : taxRegPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.business_license_no
     *
     * @return the value of tb_user_admin_authen_company.business_license_no
     *
     * @mbggenerated
     */
    public String getBusinessLicenseNo() {
        return businessLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.business_license_no
     *
     * @param businessLicenseNo the value for tb_user_admin_authen_company.business_license_no
     *
     * @mbggenerated
     */
    public void setBusinessLicenseNo(String businessLicenseNo) {
        this.businessLicenseNo = businessLicenseNo == null ? null : businessLicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.business_license_pic
     *
     * @return the value of tb_user_admin_authen_company.business_license_pic
     *
     * @mbggenerated
     */
    public String getBusinessLicensePic() {
        return businessLicensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.business_license_pic
     *
     * @param businessLicensePic the value for tb_user_admin_authen_company.business_license_pic
     *
     * @mbggenerated
     */
    public void setBusinessLicensePic(String businessLicensePic) {
        this.businessLicensePic = businessLicensePic == null ? null : businessLicensePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.create_date
     *
     * @return the value of tb_user_admin_authen_company.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.create_date
     *
     * @param createDate the value for tb_user_admin_authen_company.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_authen_company.update_date
     *
     * @return the value of tb_user_admin_authen_company.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_authen_company.update_date
     *
     * @param updateDate the value for tb_user_admin_authen_company.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}