package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class CCDayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.statday
     *
     * @mbggenerated
     */
    private Date statday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.subid
     *
     * @mbggenerated
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.abline
     *
     * @mbggenerated
     */
    private String abline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.callcnt
     *
     * @mbggenerated
     */
    private Integer callcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.succcnt
     *
     * @mbggenerated
     */
    private Integer succcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.answercnt
     *
     * @mbggenerated
     */
    private Integer answercnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.thscsum
     *
     * @mbggenerated
     */
    private Integer thscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.jfscsum
     *
     * @mbggenerated
     */
    private Integer jfscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cc_day_record.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.id
     *
     * @return the value of stat_cc_day_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.id
     *
     * @param id the value for stat_cc_day_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.statday
     *
     * @return the value of stat_cc_day_record.statday
     *
     * @mbggenerated
     */
    public Date getStatday() {
        return statday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.statday
     *
     * @param statday the value for stat_cc_day_record.statday
     *
     * @mbggenerated
     */
    public void setStatday(Date statday) {
        this.statday = statday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.appid
     *
     * @return the value of stat_cc_day_record.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.appid
     *
     * @param appid the value for stat_cc_day_record.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.subid
     *
     * @return the value of stat_cc_day_record.subid
     *
     * @mbggenerated
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.subid
     *
     * @param subid the value for stat_cc_day_record.subid
     *
     * @mbggenerated
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.feeid
     *
     * @return the value of stat_cc_day_record.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.feeid
     *
     * @param feeid the value for stat_cc_day_record.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.abline
     *
     * @return the value of stat_cc_day_record.abline
     *
     * @mbggenerated
     */
    public String getAbline() {
        return abline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.abline
     *
     * @param abline the value for stat_cc_day_record.abline
     *
     * @mbggenerated
     */
    public void setAbline(String abline) {
        this.abline = abline == null ? null : abline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.operator
     *
     * @return the value of stat_cc_day_record.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.operator
     *
     * @param operator the value for stat_cc_day_record.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.pname
     *
     * @return the value of stat_cc_day_record.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.pname
     *
     * @param pname the value for stat_cc_day_record.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.cname
     *
     * @return the value of stat_cc_day_record.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.cname
     *
     * @param cname the value for stat_cc_day_record.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.callcnt
     *
     * @return the value of stat_cc_day_record.callcnt
     *
     * @mbggenerated
     */
    public Integer getCallcnt() {
        return callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.callcnt
     *
     * @param callcnt the value for stat_cc_day_record.callcnt
     *
     * @mbggenerated
     */
    public void setCallcnt(Integer callcnt) {
        this.callcnt = callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.succcnt
     *
     * @return the value of stat_cc_day_record.succcnt
     *
     * @mbggenerated
     */
    public Integer getSucccnt() {
        return succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.succcnt
     *
     * @param succcnt the value for stat_cc_day_record.succcnt
     *
     * @mbggenerated
     */
    public void setSucccnt(Integer succcnt) {
        this.succcnt = succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.answercnt
     *
     * @return the value of stat_cc_day_record.answercnt
     *
     * @mbggenerated
     */
    public Integer getAnswercnt() {
        return answercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.answercnt
     *
     * @param answercnt the value for stat_cc_day_record.answercnt
     *
     * @mbggenerated
     */
    public void setAnswercnt(Integer answercnt) {
        this.answercnt = answercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.thscsum
     *
     * @return the value of stat_cc_day_record.thscsum
     *
     * @mbggenerated
     */
    public Integer getThscsum() {
        return thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.thscsum
     *
     * @param thscsum the value for stat_cc_day_record.thscsum
     *
     * @mbggenerated
     */
    public void setThscsum(Integer thscsum) {
        this.thscsum = thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.jfscsum
     *
     * @return the value of stat_cc_day_record.jfscsum
     *
     * @mbggenerated
     */
    public Integer getJfscsum() {
        return jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.jfscsum
     *
     * @param jfscsum the value for stat_cc_day_record.jfscsum
     *
     * @mbggenerated
     */
    public void setJfscsum(Integer jfscsum) {
        this.jfscsum = jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cc_day_record.fee
     *
     * @return the value of stat_cc_day_record.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cc_day_record.fee
     *
     * @param fee the value for stat_cc_day_record.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }
}