package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class RestHourRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.stathour
     *
     * @mbggenerated
     */
    private Date stathour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.abline
     *
     * @mbggenerated
     */
    private String abline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.callcnt
     *
     * @mbggenerated
     */
    private Integer callcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.succcnt
     *
     * @mbggenerated
     */
    private Integer succcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.thscsum
     *
     * @mbggenerated
     */
    private Integer thscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.jfscsum
     *
     * @mbggenerated
     */
    private Integer jfscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.rcd_cnt
     *
     * @mbggenerated
     */
    private Integer rcdCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.rcd_time
     *
     * @mbggenerated
     */
    private Integer rcdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.rcd_bill_cnt
     *
     * @mbggenerated
     */
    private Integer rcdBillCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.recordingfee
     *
     * @mbggenerated
     */
    private BigDecimal recordingfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_rest_hour_record.answercnt
     *
     * @mbggenerated
     */
    private Integer answercnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.id
     *
     * @return the value of stat_rest_hour_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.id
     *
     * @param id the value for stat_rest_hour_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.stathour
     *
     * @return the value of stat_rest_hour_record.stathour
     *
     * @mbggenerated
     */
    public Date getStathour() {
        return stathour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.stathour
     *
     * @param stathour the value for stat_rest_hour_record.stathour
     *
     * @mbggenerated
     */
    public void setStathour(Date stathour) {
        this.stathour = stathour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.feeid
     *
     * @return the value of stat_rest_hour_record.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.feeid
     *
     * @param feeid the value for stat_rest_hour_record.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.abline
     *
     * @return the value of stat_rest_hour_record.abline
     *
     * @mbggenerated
     */
    public String getAbline() {
        return abline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.abline
     *
     * @param abline the value for stat_rest_hour_record.abline
     *
     * @mbggenerated
     */
    public void setAbline(String abline) {
        this.abline = abline == null ? null : abline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.callcnt
     *
     * @return the value of stat_rest_hour_record.callcnt
     *
     * @mbggenerated
     */
    public Integer getCallcnt() {
        return callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.callcnt
     *
     * @param callcnt the value for stat_rest_hour_record.callcnt
     *
     * @mbggenerated
     */
    public void setCallcnt(Integer callcnt) {
        this.callcnt = callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.succcnt
     *
     * @return the value of stat_rest_hour_record.succcnt
     *
     * @mbggenerated
     */
    public Integer getSucccnt() {
        return succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.succcnt
     *
     * @param succcnt the value for stat_rest_hour_record.succcnt
     *
     * @mbggenerated
     */
    public void setSucccnt(Integer succcnt) {
        this.succcnt = succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.thscsum
     *
     * @return the value of stat_rest_hour_record.thscsum
     *
     * @mbggenerated
     */
    public Integer getThscsum() {
        return thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.thscsum
     *
     * @param thscsum the value for stat_rest_hour_record.thscsum
     *
     * @mbggenerated
     */
    public void setThscsum(Integer thscsum) {
        this.thscsum = thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.jfscsum
     *
     * @return the value of stat_rest_hour_record.jfscsum
     *
     * @mbggenerated
     */
    public Integer getJfscsum() {
        return jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.jfscsum
     *
     * @param jfscsum the value for stat_rest_hour_record.jfscsum
     *
     * @mbggenerated
     */
    public void setJfscsum(Integer jfscsum) {
        this.jfscsum = jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.rcd_cnt
     *
     * @return the value of stat_rest_hour_record.rcd_cnt
     *
     * @mbggenerated
     */
    public Integer getRcdCnt() {
        return rcdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.rcd_cnt
     *
     * @param rcdCnt the value for stat_rest_hour_record.rcd_cnt
     *
     * @mbggenerated
     */
    public void setRcdCnt(Integer rcdCnt) {
        this.rcdCnt = rcdCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.rcd_time
     *
     * @return the value of stat_rest_hour_record.rcd_time
     *
     * @mbggenerated
     */
    public Integer getRcdTime() {
        return rcdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.rcd_time
     *
     * @param rcdTime the value for stat_rest_hour_record.rcd_time
     *
     * @mbggenerated
     */
    public void setRcdTime(Integer rcdTime) {
        this.rcdTime = rcdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.rcd_bill_cnt
     *
     * @return the value of stat_rest_hour_record.rcd_bill_cnt
     *
     * @mbggenerated
     */
    public Integer getRcdBillCnt() {
        return rcdBillCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.rcd_bill_cnt
     *
     * @param rcdBillCnt the value for stat_rest_hour_record.rcd_bill_cnt
     *
     * @mbggenerated
     */
    public void setRcdBillCnt(Integer rcdBillCnt) {
        this.rcdBillCnt = rcdBillCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.fee
     *
     * @return the value of stat_rest_hour_record.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.fee
     *
     * @param fee the value for stat_rest_hour_record.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.recordingfee
     *
     * @return the value of stat_rest_hour_record.recordingfee
     *
     * @mbggenerated
     */
    public BigDecimal getRecordingfee() {
        return recordingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.recordingfee
     *
     * @param recordingfee the value for stat_rest_hour_record.recordingfee
     *
     * @mbggenerated
     */
    public void setRecordingfee(BigDecimal recordingfee) {
        this.recordingfee = recordingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_rest_hour_record.answercnt
     *
     * @return the value of stat_rest_hour_record.answercnt
     *
     * @mbggenerated
     */
    public Integer getAnswercnt() {
        return answercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_rest_hour_record.answercnt
     *
     * @param answercnt the value for stat_rest_hour_record.answercnt
     *
     * @mbggenerated
     */
    public void setAnswercnt(Integer answercnt) {
        this.answercnt = answercnt;
    }
}