package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class CallRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.forever
     *
     * @mbggenerated
     */
    private Boolean forever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.fee_mode
     *
     * @mbggenerated
     */
    private String feeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.callin
     *
     * @mbggenerated
     */
    private BigDecimal callin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.callin_discount
     *
     * @mbggenerated
     */
    private Integer callinDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.callout
     *
     * @mbggenerated
     */
    private BigDecimal callout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.callout_discount
     *
     * @mbggenerated
     */
    private Integer calloutDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.relay_rent
     *
     * @mbggenerated
     */
    private BigDecimal relayRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.relay_cnt
     *
     * @mbggenerated
     */
    private Integer relayCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.min_consume
     *
     * @mbggenerated
     */
    private BigDecimal minConsume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.discount
     *
     * @mbggenerated
     */
    private Byte discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_call_rate.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.feeid
     *
     * @return the value of rms_call_rate.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.feeid
     *
     * @param feeid the value for rms_call_rate.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.start_date
     *
     * @return the value of rms_call_rate.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.start_date
     *
     * @param startDate the value for rms_call_rate.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.end_date
     *
     * @return the value of rms_call_rate.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.end_date
     *
     * @param endDate the value for rms_call_rate.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.forever
     *
     * @return the value of rms_call_rate.forever
     *
     * @mbggenerated
     */
    public Boolean getForever() {
        return forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.forever
     *
     * @param forever the value for rms_call_rate.forever
     *
     * @mbggenerated
     */
    public void setForever(Boolean forever) {
        this.forever = forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.fee_mode
     *
     * @return the value of rms_call_rate.fee_mode
     *
     * @mbggenerated
     */
    public String getFeeMode() {
        return feeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.fee_mode
     *
     * @param feeMode the value for rms_call_rate.fee_mode
     *
     * @mbggenerated
     */
    public void setFeeMode(String feeMode) {
        this.feeMode = feeMode == null ? null : feeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.callin
     *
     * @return the value of rms_call_rate.callin
     *
     * @mbggenerated
     */
    public BigDecimal getCallin() {
        return callin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.callin
     *
     * @param callin the value for rms_call_rate.callin
     *
     * @mbggenerated
     */
    public void setCallin(BigDecimal callin) {
        this.callin = callin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.callin_discount
     *
     * @return the value of rms_call_rate.callin_discount
     *
     * @mbggenerated
     */
    public Integer getCallinDiscount() {
        return callinDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.callin_discount
     *
     * @param callinDiscount the value for rms_call_rate.callin_discount
     *
     * @mbggenerated
     */
    public void setCallinDiscount(Integer callinDiscount) {
        this.callinDiscount = callinDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.callout
     *
     * @return the value of rms_call_rate.callout
     *
     * @mbggenerated
     */
    public BigDecimal getCallout() {
        return callout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.callout
     *
     * @param callout the value for rms_call_rate.callout
     *
     * @mbggenerated
     */
    public void setCallout(BigDecimal callout) {
        this.callout = callout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.callout_discount
     *
     * @return the value of rms_call_rate.callout_discount
     *
     * @mbggenerated
     */
    public Integer getCalloutDiscount() {
        return calloutDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.callout_discount
     *
     * @param calloutDiscount the value for rms_call_rate.callout_discount
     *
     * @mbggenerated
     */
    public void setCalloutDiscount(Integer calloutDiscount) {
        this.calloutDiscount = calloutDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.relay_rent
     *
     * @return the value of rms_call_rate.relay_rent
     *
     * @mbggenerated
     */
    public BigDecimal getRelayRent() {
        return relayRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.relay_rent
     *
     * @param relayRent the value for rms_call_rate.relay_rent
     *
     * @mbggenerated
     */
    public void setRelayRent(BigDecimal relayRent) {
        this.relayRent = relayRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.relay_cnt
     *
     * @return the value of rms_call_rate.relay_cnt
     *
     * @mbggenerated
     */
    public Integer getRelayCnt() {
        return relayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.relay_cnt
     *
     * @param relayCnt the value for rms_call_rate.relay_cnt
     *
     * @mbggenerated
     */
    public void setRelayCnt(Integer relayCnt) {
        this.relayCnt = relayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.min_consume
     *
     * @return the value of rms_call_rate.min_consume
     *
     * @mbggenerated
     */
    public BigDecimal getMinConsume() {
        return minConsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.min_consume
     *
     * @param minConsume the value for rms_call_rate.min_consume
     *
     * @mbggenerated
     */
    public void setMinConsume(BigDecimal minConsume) {
        this.minConsume = minConsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.discount
     *
     * @return the value of rms_call_rate.discount
     *
     * @mbggenerated
     */
    public Byte getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.discount
     *
     * @param discount the value for rms_call_rate.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Byte discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_call_rate.addtime
     *
     * @return the value of rms_call_rate.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_call_rate.addtime
     *
     * @param addtime the value for rms_call_rate.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}