package com.e9cloud.mybatis.domain;

import java.util.Date;

public class CcInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.subid
     *
     * @mbggenerated
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.ccname
     *
     * @mbggenerated
     */
    private String ccname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.relay1
     *
     * @mbggenerated
     */
    private String relay1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.relay2
     *
     * @mbggenerated
     */
    private String relay2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.life_relay
     *
     * @mbggenerated
     */

    private String lifeRelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.cco_max_num
     *
     * @mbggenerated
     */
    private Integer ccoMaxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.dtmf_num
     *
     * @mbggenerated
     */
    private String dtmfNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.default_cc
     *
     * @mbggenerated
     */
    private Boolean defaultCc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cc_info.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.id
     *
     * @return the value of tb_cc_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.id
     *
     * @param id the value for tb_cc_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.sid
     *
     * @return the value of tb_cc_info.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.sid
     *
     * @param sid the value for tb_cc_info.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.appid
     *
     * @return the value of tb_cc_info.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.appid
     *
     * @param appid the value for tb_cc_info.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.subid
     *
     * @return the value of tb_cc_info.subid
     *
     * @mbggenerated
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.subid
     *
     * @param subid the value for tb_cc_info.subid
     *
     * @mbggenerated
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.ccname
     *
     * @return the value of tb_cc_info.ccname
     *
     * @mbggenerated
     */
    public String getCcname() {
        return ccname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.ccname
     *
     * @param ccname the value for tb_cc_info.ccname
     *
     * @mbggenerated
     */
    public void setCcname(String ccname) {
        this.ccname = ccname == null ? null : ccname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.relay1
     *
     * @return the value of tb_cc_info.relay1
     *
     * @mbggenerated
     */
    public String getRelay1() {
        return relay1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.relay1
     *
     * @param relay1 the value for tb_cc_info.relay1
     *
     * @mbggenerated
     */
    public void setRelay1(String relay1) {
        this.relay1 = relay1 == null ? null : relay1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.relay2
     *
     * @return the value of tb_cc_info.relay2
     *
     * @mbggenerated
     */
    public String getRelay2() {
        return relay2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.relay2
     *
     * @param relay2 the value for tb_cc_info.relay2
     *
     * @mbggenerated
     */
    public void setRelay2(String relay2) {
        this.relay2 = relay2 == null ? null : relay2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.life_relay
     *
     * @return the value of tb_cc_info.life_relay
     *
     * @mbggenerated
     */
    public String getLifeRelay() {
        return lifeRelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.life_relay
     *
     * @param lifeRelay the value for tb_cc_info.life_relay
     *
     * @mbggenerated
     */
    public void setLifeRelay(String lifeRelay) {
        this.lifeRelay = lifeRelay == null ? null : lifeRelay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.cco_max_num
     *
     * @return the value of tb_cc_info.cco_max_num
     *
     * @mbggenerated
     */
    public Integer getCcoMaxNum() {
        return ccoMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.cco_max_num
     *
     * @param ccoMaxNum the value for tb_cc_info.cco_max_num
     *
     * @mbggenerated
     */
    public void setCcoMaxNum(Integer ccoMaxNum) {
        this.ccoMaxNum = ccoMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.dtmf_num
     *
     * @return the value of tb_cc_info.dtmf_num
     *
     * @mbggenerated
     */
    public String getDtmfNum() {
        return dtmfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.dtmf_num
     *
     * @param dtmfNum the value for tb_cc_info.dtmf_num
     *
     * @mbggenerated
     */
    public void setDtmfNum(String dtmfNum) {
        this.dtmfNum = dtmfNum == null ? null : dtmfNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.default_cc
     *
     * @return the value of tb_cc_info.default_cc
     *
     * @mbggenerated
     */
    public Boolean getDefaultCc() {
        return defaultCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.default_cc
     *
     * @param defaultCc the value for tb_cc_info.default_cc
     *
     * @mbggenerated
     */
    public void setDefaultCc(Boolean defaultCc) {
        this.defaultCc = defaultCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.status
     *
     * @return the value of tb_cc_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.status
     *
     * @param status the value for tb_cc_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.remark
     *
     * @return the value of tb_cc_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.remark
     *
     * @param remark the value for tb_cc_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cc_info.ctime
     *
     * @return the value of tb_cc_info.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cc_info.ctime
     *
     * @param ctime the value for tb_cc_info.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}