package com.e9cloud.mybatis.domain;

public class CityCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city_area_code.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city_area_code.city
     *
     * @mbggenerated
     */

    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_city_area_code.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city_area_code.id
     *
     * @return the value of tb_city_area_code.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city_area_code.id
     *
     * @param id the value for tb_city_area_code.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city_area_code.city
     *
     * @return the value of tb_city_area_code.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city_area_code.city
     *
     * @param city the value for tb_city_area_code.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city_area_code.area_code
     *
     * @return the value of tb_city_area_code.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city_area_code.area_code
     *
     * @param areaCode the value for tb_city_area_code.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}