package com.e9cloud.mybatis.domain;

import java.util.Date;

public class EccAppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.id
     *
     * @mbggenerated
     */

    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.switchboard_id
     *
     * @mbggenerated
     */
    private String switchboardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.cityid
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.transfer
     *
     * @mbggenerated
     */
    private Boolean transfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.transfer_num
     *
     * @mbggenerated
     */
    private String transferNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.ivr_voice_need
     *
     * @mbggenerated
     */
    private Boolean ivrVoiceNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.ivr_voice_name
     *
     * @mbggenerated
     */
    private String ivrVoiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.ivr_voice_url
     *
     * @mbggenerated
     */
    private String ivrVoiceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_info_ecc.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.id
     *
     * @return the value of tb_app_info_ecc.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.id
     *
     * @param id the value for tb_app_info_ecc.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.appid
     *
     * @return the value of tb_app_info_ecc.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.appid
     *
     * @param appid the value for tb_app_info_ecc.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.switchboard_id
     *
     * @return the value of tb_app_info_ecc.switchboard_id
     *
     * @mbggenerated
     */
    public String getSwitchboardId() {
        return switchboardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.switchboard_id
     *
     * @param switchboardId the value for tb_app_info_ecc.switchboard_id
     *
     * @mbggenerated
     */
    public void setSwitchboardId(String switchboardId) {
        this.switchboardId = switchboardId == null ? null : switchboardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.cityid
     *
     * @return the value of tb_app_info_ecc.cityid
     *
     * @mbggenerated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.cityid
     *
     * @param cityid the value for tb_app_info_ecc.cityid
     *
     * @mbggenerated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.transfer
     *
     * @return the value of tb_app_info_ecc.transfer
     *
     * @mbggenerated
     */
    public Boolean getTransfer() {
        return transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.transfer
     *
     * @param transfer the value for tb_app_info_ecc.transfer
     *
     * @mbggenerated
     */
    public void setTransfer(Boolean transfer) {
        this.transfer = transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.transfer_num
     *
     * @return the value of tb_app_info_ecc.transfer_num
     *
     * @mbggenerated
     */
    public String getTransferNum() {
        return transferNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.transfer_num
     *
     * @param transferNum the value for tb_app_info_ecc.transfer_num
     *
     * @mbggenerated
     */
    public void setTransferNum(String transferNum) {
        this.transferNum = transferNum == null ? null : transferNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.ivr_voice_need
     *
     * @return the value of tb_app_info_ecc.ivr_voice_need
     *
     * @mbggenerated
     */
    public Boolean getIvrVoiceNeed() {
        return ivrVoiceNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.ivr_voice_need
     *
     * @param ivrVoiceNeed the value for tb_app_info_ecc.ivr_voice_need
     *
     * @mbggenerated
     */
    public void setIvrVoiceNeed(Boolean ivrVoiceNeed) {
        this.ivrVoiceNeed = ivrVoiceNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.ivr_voice_name
     *
     * @return the value of tb_app_info_ecc.ivr_voice_name
     *
     * @mbggenerated
     */
    public String getIvrVoiceName() {
        return ivrVoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.ivr_voice_name
     *
     * @param ivrVoiceName the value for tb_app_info_ecc.ivr_voice_name
     *
     * @mbggenerated
     */
    public void setIvrVoiceName(String ivrVoiceName) {
        this.ivrVoiceName = ivrVoiceName == null ? null : ivrVoiceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.ivr_voice_url
     *
     * @return the value of tb_app_info_ecc.ivr_voice_url
     *
     * @mbggenerated
     */
    public String getIvrVoiceUrl() {
        return ivrVoiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.ivr_voice_url
     *
     * @param ivrVoiceUrl the value for tb_app_info_ecc.ivr_voice_url
     *
     * @mbggenerated
     */
    public void setIvrVoiceUrl(String ivrVoiceUrl) {
        this.ivrVoiceUrl = ivrVoiceUrl == null ? null : ivrVoiceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.addtime
     *
     * @return the value of tb_app_info_ecc.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.addtime
     *
     * @param addtime the value for tb_app_info_ecc.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_info_ecc.updatetime
     *
     * @return the value of tb_app_info_ecc.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_info_ecc.updatetime
     *
     * @param updatetime the value for tb_app_info_ecc.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}