package com.e9cloud.mybatis.domain;

import java.util.Date;

public class EccExtention {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.eccid
     *
     * @mbggenerated
     */
    private String eccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.sub_num
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.num_type
     *
     * @mbggenerated
     */
    private String numType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.sipphone_id
     *
     * @mbggenerated
     */
    private String sipphoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.fixphone_id
     *
     * @mbggenerated
     */
    private String fixphoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.shownum_id
     *
     * @mbggenerated
     */
    private String shownumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.long_distance_flag
     *
     * @mbggenerated
     */
    private String longDistanceFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.call_switch_flag
     *
     * @mbggenerated
     */
    private String callSwitchFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_extention.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.id
     *
     * @return the value of tb_ecc_extention.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.id
     *
     * @param id the value for tb_ecc_extention.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.appid
     *
     * @return the value of tb_ecc_extention.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.appid
     *
     * @param appid the value for tb_ecc_extention.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.eccid
     *
     * @return the value of tb_ecc_extention.eccid
     *
     * @mbggenerated
     */
    public String getEccid() {
        return eccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.eccid
     *
     * @param eccid the value for tb_ecc_extention.eccid
     *
     * @mbggenerated
     */
    public void setEccid(String eccid) {
        this.eccid = eccid == null ? null : eccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.sub_num
     *
     * @return the value of tb_ecc_extention.sub_num
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.sub_num
     *
     * @param subNum the value for tb_ecc_extention.sub_num
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.num_type
     *
     * @return the value of tb_ecc_extention.num_type
     *
     * @mbggenerated
     */
    public String getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.num_type
     *
     * @param numType the value for tb_ecc_extention.num_type
     *
     * @mbggenerated
     */
    public void setNumType(String numType) {
        this.numType = numType == null ? null : numType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.sipphone_id
     *
     * @return the value of tb_ecc_extention.sipphone_id
     *
     * @mbggenerated
     */
    public String getSipphoneId() {
        return sipphoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.sipphone_id
     *
     * @param sipphoneId the value for tb_ecc_extention.sipphone_id
     *
     * @mbggenerated
     */
    public void setSipphoneId(String sipphoneId) {
        this.sipphoneId = sipphoneId == null ? null : sipphoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.fixphone_id
     *
     * @return the value of tb_ecc_extention.fixphone_id
     *
     * @mbggenerated
     */
    public String getFixphoneId() {
        return fixphoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.fixphone_id
     *
     * @param fixphoneId the value for tb_ecc_extention.fixphone_id
     *
     * @mbggenerated
     */
    public void setFixphoneId(String fixphoneId) {
        this.fixphoneId = fixphoneId == null ? null : fixphoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.shownum_id
     *
     * @return the value of tb_ecc_extention.shownum_id
     *
     * @mbggenerated
     */
    public String getShownumId() {
        return shownumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.shownum_id
     *
     * @param shownumId the value for tb_ecc_extention.shownum_id
     *
     * @mbggenerated
     */
    public void setShownumId(String shownumId) {
        this.shownumId = shownumId == null ? null : shownumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.long_distance_flag
     *
     * @return the value of tb_ecc_extention.long_distance_flag
     *
     * @mbggenerated
     */
    public String getLongDistanceFlag() {
        return longDistanceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.long_distance_flag
     *
     * @param longDistanceFlag the value for tb_ecc_extention.long_distance_flag
     *
     * @mbggenerated
     */
    public void setLongDistanceFlag(String longDistanceFlag) {
        this.longDistanceFlag = longDistanceFlag == null ? null : longDistanceFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.call_switch_flag
     *
     * @return the value of tb_ecc_extention.call_switch_flag
     *
     * @mbggenerated
     */
    public String getCallSwitchFlag() {
        return callSwitchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.call_switch_flag
     *
     * @param callSwitchFlag the value for tb_ecc_extention.call_switch_flag
     *
     * @mbggenerated
     */
    public void setCallSwitchFlag(String callSwitchFlag) {
        this.callSwitchFlag = callSwitchFlag == null ? null : callSwitchFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.status
     *
     * @return the value of tb_ecc_extention.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.status
     *
     * @param status the value for tb_ecc_extention.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.addtime
     *
     * @return the value of tb_ecc_extention.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.addtime
     *
     * @param addtime the value for tb_ecc_extention.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_extention.updatetime
     *
     * @return the value of tb_ecc_extention.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_extention.updatetime
     *
     * @param updatetime the value for tb_ecc_extention.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}