package com.e9cloud.mybatis.domain;

import java.util.Date;

public class EccFixphone {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.eccid
     *
     * @mbggenerated
     */
    private String eccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.cityid
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.num_type
     *
     * @mbggenerated
     */
    private String numType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_fixphone.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.id
     *
     * @return the value of tb_ecc_fixphone.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.id
     *
     * @param id the value for tb_ecc_fixphone.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.appid
     *
     * @return the value of tb_ecc_fixphone.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.appid
     *
     * @param appid the value for tb_ecc_fixphone.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.eccid
     *
     * @return the value of tb_ecc_fixphone.eccid
     *
     * @mbggenerated
     */
    public String getEccid() {
        return eccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.eccid
     *
     * @param eccid the value for tb_ecc_fixphone.eccid
     *
     * @mbggenerated
     */
    public void setEccid(String eccid) {
        this.eccid = eccid == null ? null : eccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.cityid
     *
     * @return the value of tb_ecc_fixphone.cityid
     *
     * @mbggenerated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.cityid
     *
     * @param cityid the value for tb_ecc_fixphone.cityid
     *
     * @mbggenerated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.num_type
     *
     * @return the value of tb_ecc_fixphone.num_type
     *
     * @mbggenerated
     */
    public String getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.num_type
     *
     * @param numType the value for tb_ecc_fixphone.num_type
     *
     * @mbggenerated
     */
    public void setNumType(String numType) {
        this.numType = numType == null ? null : numType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.number
     *
     * @return the value of tb_ecc_fixphone.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.number
     *
     * @param number the value for tb_ecc_fixphone.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.status
     *
     * @return the value of tb_ecc_fixphone.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.status
     *
     * @param status the value for tb_ecc_fixphone.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.addtime
     *
     * @return the value of tb_ecc_fixphone.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.addtime
     *
     * @param addtime the value for tb_ecc_fixphone.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_fixphone.updatetime
     *
     * @return the value of tb_ecc_fixphone.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_fixphone.updatetime
     *
     * @param updatetime the value for tb_ecc_fixphone.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}