package com.e9cloud.mybatis.domain;

import java.util.Date;

public class EccSipphone {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.sip_phone
     *
     * @mbggenerated
     */
    private String sipPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.impi
     *
     * @mbggenerated
     */
    private String impi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.cityid
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.ip_port
     *
     * @mbggenerated
     */
    private String ipPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.sip_realm
     *
     * @mbggenerated
     */
    private String sipRealm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ecc_sipphone.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.id
     *
     * @return the value of tb_ecc_sipphone.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.id
     *
     * @param id the value for tb_ecc_sipphone.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.sip_phone
     *
     * @return the value of tb_ecc_sipphone.sip_phone
     *
     * @mbggenerated
     */
    public String getSipPhone() {
        return sipPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.sip_phone
     *
     * @param sipPhone the value for tb_ecc_sipphone.sip_phone
     *
     * @mbggenerated
     */
    public void setSipPhone(String sipPhone) {
        this.sipPhone = sipPhone == null ? null : sipPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.impi
     *
     * @return the value of tb_ecc_sipphone.impi
     *
     * @mbggenerated
     */
    public String getImpi() {
        return impi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.impi
     *
     * @param impi the value for tb_ecc_sipphone.impi
     *
     * @mbggenerated
     */
    public void setImpi(String impi) {
        this.impi = impi == null ? null : impi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.cityid
     *
     * @return the value of tb_ecc_sipphone.cityid
     *
     * @mbggenerated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.cityid
     *
     * @param cityid the value for tb_ecc_sipphone.cityid
     *
     * @mbggenerated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.pwd
     *
     * @return the value of tb_ecc_sipphone.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.pwd
     *
     * @param pwd the value for tb_ecc_sipphone.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.ip_port
     *
     * @return the value of tb_ecc_sipphone.ip_port
     *
     * @mbggenerated
     */
    public String getIpPort() {
        return ipPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.ip_port
     *
     * @param ipPort the value for tb_ecc_sipphone.ip_port
     *
     * @mbggenerated
     */
    public void setIpPort(String ipPort) {
        this.ipPort = ipPort == null ? null : ipPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.sip_realm
     *
     * @return the value of tb_ecc_sipphone.sip_realm
     *
     * @mbggenerated
     */
    public String getSipRealm() {
        return sipRealm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.sip_realm
     *
     * @param sipRealm the value for tb_ecc_sipphone.sip_realm
     *
     * @mbggenerated
     */
    public void setSipRealm(String sipRealm) {
        this.sipRealm = sipRealm == null ? null : sipRealm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.status
     *
     * @return the value of tb_ecc_sipphone.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.status
     *
     * @param status the value for tb_ecc_sipphone.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.addtime
     *
     * @return the value of tb_ecc_sipphone.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.addtime
     *
     * @param addtime the value for tb_ecc_sipphone.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ecc_sipphone.updatetime
     *
     * @return the value of tb_ecc_sipphone.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ecc_sipphone.updatetime
     *
     * @param updatetime the value for tb_ecc_sipphone.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}