package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class IvrDayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.id
     *
     * @mbggenerated
     */

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.statday
     *
     * @mbggenerated
     */
    private Date statday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.rcdtype
     *
     * @mbggenerated
     */
    private String rcdtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.abline
     *
     * @mbggenerated
     */
    private String abline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.callcnt
     *
     * @mbggenerated
     */
    private Integer callcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.succcnt
     *
     * @mbggenerated
     */
    private Integer succcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.answercnt
     *
     * @mbggenerated
     */
    private Integer answercnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.thscsum
     *
     * @mbggenerated
     */
    private Integer thscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.jfscsum
     *
     * @mbggenerated
     */
    private Integer jfscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.lyscsum
     *
     * @mbggenerated
     */
    private Integer lyscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.jflyscsum
     *
     * @mbggenerated
     */
    private Integer jflyscsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.recordingfee
     *
     * @mbggenerated
     */
    private BigDecimal recordingfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ivr_day_record.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.id
     *
     * @return the value of stat_ivr_day_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.id
     *
     * @param id the value for stat_ivr_day_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.statday
     *
     * @return the value of stat_ivr_day_record.statday
     *
     * @mbggenerated
     */
    public Date getStatday() {
        return statday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.statday
     *
     * @param statday the value for stat_ivr_day_record.statday
     *
     * @mbggenerated
     */
    public void setStatday(Date statday) {
        this.statday = statday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.rcdtype
     *
     * @return the value of stat_ivr_day_record.rcdtype
     *
     * @mbggenerated
     */
    public String getRcdtype() {
        return rcdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.rcdtype
     *
     * @param rcdtype the value for stat_ivr_day_record.rcdtype
     *
     * @mbggenerated
     */
    public void setRcdtype(String rcdtype) {
        this.rcdtype = rcdtype == null ? null : rcdtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.abline
     *
     * @return the value of stat_ivr_day_record.abline
     *
     * @mbggenerated
     */
    public String getAbline() {
        return abline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.abline
     *
     * @param abline the value for stat_ivr_day_record.abline
     *
     * @mbggenerated
     */
    public void setAbline(String abline) {
        this.abline = abline == null ? null : abline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.sid
     *
     * @return the value of stat_ivr_day_record.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.sid
     *
     * @param sid the value for stat_ivr_day_record.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.feeid
     *
     * @return the value of stat_ivr_day_record.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.feeid
     *
     * @param feeid the value for stat_ivr_day_record.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.appid
     *
     * @return the value of stat_ivr_day_record.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.appid
     *
     * @param appid the value for stat_ivr_day_record.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.callcnt
     *
     * @return the value of stat_ivr_day_record.callcnt
     *
     * @mbggenerated
     */
    public Integer getCallcnt() {
        return callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.callcnt
     *
     * @param callcnt the value for stat_ivr_day_record.callcnt
     *
     * @mbggenerated
     */
    public void setCallcnt(Integer callcnt) {
        this.callcnt = callcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.succcnt
     *
     * @return the value of stat_ivr_day_record.succcnt
     *
     * @mbggenerated
     */
    public Integer getSucccnt() {
        return succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.succcnt
     *
     * @param succcnt the value for stat_ivr_day_record.succcnt
     *
     * @mbggenerated
     */
    public void setSucccnt(Integer succcnt) {
        this.succcnt = succcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.answercnt
     *
     * @return the value of stat_ivr_day_record.answercnt
     *
     * @mbggenerated
     */
    public Integer getAnswercnt() {
        return answercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.answercnt
     *
     * @param answercnt the value for stat_ivr_day_record.answercnt
     *
     * @mbggenerated
     */
    public void setAnswercnt(Integer answercnt) {
        this.answercnt = answercnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.thscsum
     *
     * @return the value of stat_ivr_day_record.thscsum
     *
     * @mbggenerated
     */
    public Integer getThscsum() {
        return thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.thscsum
     *
     * @param thscsum the value for stat_ivr_day_record.thscsum
     *
     * @mbggenerated
     */
    public void setThscsum(Integer thscsum) {
        this.thscsum = thscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.jfscsum
     *
     * @return the value of stat_ivr_day_record.jfscsum
     *
     * @mbggenerated
     */
    public Integer getJfscsum() {
        return jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.jfscsum
     *
     * @param jfscsum the value for stat_ivr_day_record.jfscsum
     *
     * @mbggenerated
     */
    public void setJfscsum(Integer jfscsum) {
        this.jfscsum = jfscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.lyscsum
     *
     * @return the value of stat_ivr_day_record.lyscsum
     *
     * @mbggenerated
     */
    public Integer getLyscsum() {
        return lyscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.lyscsum
     *
     * @param lyscsum the value for stat_ivr_day_record.lyscsum
     *
     * @mbggenerated
     */
    public void setLyscsum(Integer lyscsum) {
        this.lyscsum = lyscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.jflyscsum
     *
     * @return the value of stat_ivr_day_record.jflyscsum
     *
     * @mbggenerated
     */
    public Integer getJflyscsum() {
        return jflyscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.jflyscsum
     *
     * @param jflyscsum the value for stat_ivr_day_record.jflyscsum
     *
     * @mbggenerated
     */
    public void setJflyscsum(Integer jflyscsum) {
        this.jflyscsum = jflyscsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.fee
     *
     * @return the value of stat_ivr_day_record.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.fee
     *
     * @param fee the value for stat_ivr_day_record.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.recordingfee
     *
     * @return the value of stat_ivr_day_record.recordingfee
     *
     * @mbggenerated
     */
    public BigDecimal getRecordingfee() {
        return recordingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.recordingfee
     *
     * @param recordingfee the value for stat_ivr_day_record.recordingfee
     *
     * @mbggenerated
     */
    public void setRecordingfee(BigDecimal recordingfee) {
        this.recordingfee = recordingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ivr_day_record.ctime
     *
     * @return the value of stat_ivr_day_record.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ivr_day_record.ctime
     *
     * @param ctime the value for stat_ivr_day_record.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}