package com.e9cloud.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class RestRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.forever
     *
     * @mbggenerated
     */
    private Boolean forever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.fee_mode
     *
     * @mbggenerated
     */
    private String feeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.rest
     *
     * @mbggenerated
     */
    private BigDecimal rest;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.rest_discount
     *
     * @mbggenerated
     */
    private Integer restDiscount;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.rest
     *
     * @mbggenerated
     */
    private BigDecimal restA;

    public BigDecimal getRestA() {
        return restA;
    }

    public void setRestA(BigDecimal restA) {
        this.restA = restA;
    }




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.rest_discount
     *
     * @mbggenerated
     */
    private Integer restADiscount;

    public Integer getRestADiscount() {
        return restADiscount;
    }

    public void setRestADiscount(Integer restADiscount) {
        this.restADiscount = restADiscount;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.recording
     *
     * @mbggenerated
     */
    private BigDecimal recording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.recording_discount
     *
     * @mbggenerated
     */
    private Integer recordingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_rest_rate.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.feeid
     *
     * @return the value of rms_rest_rate.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.feeid
     *
     * @param feeid the value for rms_rest_rate.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.start_date
     *
     * @return the value of rms_rest_rate.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.start_date
     *
     * @param startDate the value for rms_rest_rate.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.end_date
     *
     * @return the value of rms_rest_rate.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.end_date
     *
     * @param endDate the value for rms_rest_rate.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.forever
     *
     * @return the value of rms_rest_rate.forever
     *
     * @mbggenerated
     */
    public Boolean getForever() {
        return forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.forever
     *
     * @param forever the value for rms_rest_rate.forever
     *
     * @mbggenerated
     */
    public void setForever(Boolean forever) {
        this.forever = forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.fee_mode
     *
     * @return the value of rms_rest_rate.fee_mode
     *
     * @mbggenerated
     */
    public String getFeeMode() {
        return feeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.fee_mode
     *
     * @param feeMode the value for rms_rest_rate.fee_mode
     *
     * @mbggenerated
     */
    public void setFeeMode(String feeMode) {
        this.feeMode = feeMode == null ? null : feeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.rest
     *
     * @return the value of rms_rest_rate.rest
     *
     * @mbggenerated
     */
    public BigDecimal getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.rest
     *
     * @param rest the value for rms_rest_rate.rest
     *
     * @mbggenerated
     */
    public void setRest(BigDecimal rest) {
        this.rest = rest;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.rest_discount
     *
     * @return the value of rms_rest_rate.rest_discount
     *
     * @mbggenerated
     */
    public Integer getRestDiscount() {
        return restDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.rest_discount
     *
     * @param restDiscount the value for rms_rest_rate.rest_discount
     *
     * @mbggenerated
     */
    public void setRestDiscount(Integer restDiscount) {
        this.restDiscount = restDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.recording
     *
     * @return the value of rms_rest_rate.recording
     *
     * @mbggenerated
     */
    public BigDecimal getRecording() {
        return recording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.recording
     *
     * @param recording the value for rms_rest_rate.recording
     *
     * @mbggenerated
     */
    public void setRecording(BigDecimal recording) {
        this.recording = recording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.recording_discount
     *
     * @return the value of rms_rest_rate.recording_discount
     *
     * @mbggenerated
     */
    public Integer getRecordingDiscount() {
        return recordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.recording_discount
     *
     * @param recordingDiscount the value for rms_rest_rate.recording_discount
     *
     * @mbggenerated
     */
    public void setRecordingDiscount(Integer recordingDiscount) {
        this.recordingDiscount = recordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_rest_rate.addtime
     *
     * @return the value of rms_rest_rate.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_rest_rate.addtime
     *
     * @param addtime the value for rms_rest_rate.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}