package com.e9cloud.mybatis.domain;

import java.util.Date;

public class SpApplyNum {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.id
   *
   * @mbggenerated
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.appid
   *
   * @mbggenerated
   */
  private String appid;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.apply_id
   *
   * @mbggenerated
   */
  private String applyId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.sipphone_id
   *
   * @mbggenerated
   */
  private String sipphoneId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.fixphone_id
   *
   * @mbggenerated
   */
  private String fixphoneId;

  /* 显号表显号
   */
  private String showNum;


  private String auditShowNum;



  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.atime
   *
   * @mbggenerated
   */
  private Date atime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.audit_status
   *
   * @mbggenerated
   */
  private String auditStatus;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.audit_common
   *
   * @mbggenerated
   */
  private String auditCommon;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column tb_sp_apply_num.audit_time
   *
   * @mbggenerated
   */
  private Date auditTime;

  private String sipphone;
  private String fixphone;

  // 长途权限：00 开启，01 关闭 (默认01)
  private String longDistanceFlag;

  // 号码禁用开关：00 可用，01禁用 （默认00）
  private String  callSwitchFlag;

  //////////////////////////////////////////////////////////////

  public String getSipphone() {
    return sipphone;
  }

  public String getFixphone() {
    return fixphone;
  }

  public void setSipphone(String sipphone) {
    this.sipphone = sipphone;
  }

  public void setFixphone(String fixphone) {
    this.fixphone = fixphone;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.id
   *
   * @return the value of tb_sp_apply_num.id
   *
   * @mbggenerated
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.id
   *
   * @param id the value for tb_sp_apply_num.id
   *
   * @mbggenerated
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.appid
   *
   * @return the value of tb_sp_apply_num.appid
   *
   * @mbggenerated
   */
  public String getAppid() {
    return appid;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.appid
   *
   * @param appid the value for tb_sp_apply_num.appid
   *
   * @mbggenerated
   */
  public void setAppid(String appid) {
    this.appid = appid == null ? null : appid.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.apply_id
   *
   * @return the value of tb_sp_apply_num.apply_id
   *
   * @mbggenerated
   */
  public String getApplyId() {
    return applyId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.apply_id
   *
   * @param applyId the value for tb_sp_apply_num.apply_id
   *
   * @mbggenerated
   */
  public void setApplyId(String applyId) {
    this.applyId = applyId == null ? null : applyId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.sipphone_id
   *
   * @return the value of tb_sp_apply_num.sipphone_id
   *
   * @mbggenerated
   */
  public String getSipphoneId() {
    return sipphoneId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.sipphone_id
   *
   * @param sipphoneId the value for tb_sp_apply_num.sipphone_id
   *
   * @mbggenerated
   */
  public void setSipphoneId(String sipphoneId) {
    this.sipphoneId = sipphoneId == null ? null : sipphoneId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.fixphone_id
   *
   * @return the value of tb_sp_apply_num.fixphone_id
   *
   * @mbggenerated
   */
  public String getFixphoneId() {
    return fixphoneId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.fixphone_id
   *
   * @param fixphoneId the value for tb_sp_apply_num.fixphone_id
   *
   * @mbggenerated
   */
  public void setFixphoneId(String fixphoneId) {
    this.fixphoneId = fixphoneId == null ? null : fixphoneId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.show_num
   *
   * @return the value of tb_sp_apply_num.show_num
   *
   * @mbggenerated
   */
  public String getShowNum() {
    return showNum;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.show_num
   *
   * @param showNum the value for tb_sp_apply_num.show_num
   *
   * @mbggenerated
   */
  public void setShowNum(String showNum) {
    this.showNum = showNum == null ? null : showNum.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.atime
   *
   * @return the value of tb_sp_apply_num.atime
   *
   * @mbggenerated
   */
  public Date getAtime() {
    return atime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.atime
   *
   * @param atime the value for tb_sp_apply_num.atime
   *
   * @mbggenerated
   */
  public void setAtime(Date atime) {
    this.atime = atime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.audit_status
   *
   * @return the value of tb_sp_apply_num.audit_status
   *
   * @mbggenerated
   */
  public String getAuditStatus() {
    return auditStatus;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.audit_status
   *
   * @param auditStatus the value for tb_sp_apply_num.audit_status
   *
   * @mbggenerated
   */
  public void setAuditStatus(String auditStatus) {
    this.auditStatus = auditStatus == null ? null : auditStatus.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.audit_common
   *
   * @return the value of tb_sp_apply_num.audit_common
   *
   * @mbggenerated
   */
  public String getAuditCommon() {
    return auditCommon;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.audit_common
   *
   * @param auditCommon the value for tb_sp_apply_num.audit_common
   *
   * @mbggenerated
   */
  public void setAuditCommon(String auditCommon) {
    this.auditCommon = auditCommon == null ? null : auditCommon.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column tb_sp_apply_num.audit_time
   *
   * @return the value of tb_sp_apply_num.audit_time
   *
   * @mbggenerated
   */
  public Date getAuditTime() {
    return auditTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column tb_sp_apply_num.audit_time
   *
   * @param auditTime the value for tb_sp_apply_num.audit_time
   *
   * @mbggenerated
   */
  public void setAuditTime(Date auditTime) {
    this.auditTime = auditTime;
  }

  public void setAuditShowNum(String auditShowNum) {
    this.auditShowNum = auditShowNum;
  }

  public String getAuditShowNum() {
    return auditShowNum;
  }

  public String getLongDistanceFlag() {
    return longDistanceFlag;
  }

  public void setLongDistanceFlag(String longDistanceFlag) {
    this.longDistanceFlag = longDistanceFlag;
  }

  public String getCallSwitchFlag() {
    return callSwitchFlag;
  }

  public void setCallSwitchFlag(String callSwitchFlag) {
    this.callSwitchFlag = callSwitchFlag;
  }
}