package com.e9cloud.mybatis.domain;

import java.util.Date;

public class TempVoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.id
     *
     * @mbggenerated
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.appid
     *
     * @mbggenerated
     */
    private String appid;



    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.name
     *
     * @mbggenerated
     */
    private String name;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.audit_status
     *
     * @mbggenerated
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.audit_common
     *
     * @mbggenerated
     */
    private String auditCommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.v_url
     *
     * @mbggenerated
     */
    private String vUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.v_size
     *
     * @mbggenerated
     */
    private String vSize;


    private String vPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.t_content
     *
     * @mbggenerated
     */
    private String tContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voice_temp.atime
     *
     * @mbggenerated
     */
    private Date atime;


    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    public String getvPath() {
        return vPath;
    }

    public void setvPath(String vPath) {
        this.vPath = vPath;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.id
     *
     * @return the value of tb_voice_temp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.id
     *
     * @param id the value for tb_voice_temp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.appid
     *
     * @return the value of tb_voice_temp.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.appid
     *
     * @param appid the value for tb_voice_temp.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.name
     *
     * @return the value of tb_voice_temp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.name
     *
     * @param name the value for tb_voice_temp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.type
     *
     * @param type the value for tb_voice_temp.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.audit_status
     *
     * @return the value of tb_voice_temp.audit_status
     *
     * @mbggenerated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.audit_status
     *
     * @param auditStatus the value for tb_voice_temp.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.audit_common
     *
     * @return the value of tb_voice_temp.audit_common
     *
     * @mbggenerated
     */
    public String getAuditCommon() {
        return auditCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.audit_common
     *
     * @param auditCommon the value for tb_voice_temp.audit_common
     *
     * @mbggenerated
     */
    public void setAuditCommon(String auditCommon) {
        this.auditCommon = auditCommon == null ? null : auditCommon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.audit_time
     *
     * @return the value of tb_voice_temp.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.audit_time
     *
     * @param auditTime the value for tb_voice_temp.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.v_url
     *
     * @return the value of tb_voice_temp.v_url
     *
     * @mbggenerated
     */
    public String getvUrl() {
        return vUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.v_url
     *
     * @param vUrl the value for tb_voice_temp.v_url
     *
     * @mbggenerated
     */
    public void setvUrl(String vUrl) {
        this.vUrl = vUrl == null ? null : vUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.v_size
     *
     * @return the value of tb_voice_temp.v_size
     *
     * @mbggenerated
     */
    public String getvSize() {
        return vSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.v_size
     *
     * @param vSize the value for tb_voice_temp.v_size
     *
     * @mbggenerated
     */
    public void setvSize(String vSize) {
        this.vSize = vSize == null ? null : vSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.t_content
     *
     * @return the value of tb_voice_temp.t_content
     *
     * @mbggenerated
     */
    public String gettContent() {
        return tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.t_content
     *
     * @param tContent the value for tb_voice_temp.t_content
     *
     * @mbggenerated
     */
    public void settContent(String tContent) {
        this.tContent = tContent == null ? null : tContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voice_temp.atime
     *
     * @return the value of tb_voice_temp.atime
     *
     * @mbggenerated
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voice_temp.atime
     *
     * @param atime the value for tb_voice_temp.atime
     *
     * @mbggenerated
     */
    public void setAtime(Date atime) {
        this.atime = atime;
    }
}