package com.e9cloud.mybatis.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

public class VoiceVerifyRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.start_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.end_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.forever
     *
     * @mbggenerated
     */
    private Boolean forever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.fee_mode
     *
     * @mbggenerated
     */
    private String feeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per
     *
     * @mbggenerated
     */
    private BigDecimal per;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per_discount
     *
     * @mbggenerated
     */
    private Integer perDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per6
     *
     * @mbggenerated
     */
    private BigDecimal per6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per6_discount
     *
     * @mbggenerated
     */
    private Integer per6Discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per60
     *
     * @mbggenerated
     */
    private BigDecimal per60;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.per60_discount
     *
     * @mbggenerated
     */
    private Integer per60Discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.perx
     *
     * @mbggenerated
     */
    private BigDecimal perx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.recording
     *
     * @mbggenerated
     */
    private BigDecimal recording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.recording_discount
     *
     * @mbggenerated
     */
    private Integer recordingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_voiceverify_rate.addtime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.feeid
     *
     * @return the value of rms_voiceverify_rate.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.feeid
     *
     * @param feeid the value for rms_voiceverify_rate.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.start_date
     *
     * @return the value of rms_voiceverify_rate.start_date
     *
     * @mbggenerated
     */
    public String getStartDate() {
        if(startDate != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            return dateFormat.format(startDate);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.start_date
     *
     * @param startDate the value for rms_voiceverify_rate.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.end_date
     *
     * @return the value of rms_voiceverify_rate.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        if(endDate != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            return dateFormat.format(endDate);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.end_date
     *
     * @param endDate the value for rms_voiceverify_rate.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.forever
     *
     * @return the value of rms_voiceverify_rate.forever
     *
     * @mbggenerated
     */
    public Boolean getForever() {
        return forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.forever
     *
     * @param forever the value for rms_voiceverify_rate.forever
     *
     * @mbggenerated
     */
    public void setForever(Boolean forever) {
        this.forever = forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.fee_mode
     *
     * @return the value of rms_voiceverify_rate.fee_mode
     *
     * @mbggenerated
     */
    public String getFeeMode() {
        return feeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.fee_mode
     *
     * @param feeMode the value for rms_voiceverify_rate.fee_mode
     *
     * @mbggenerated
     */
    public void setFeeMode(String feeMode) {
        this.feeMode = feeMode == null ? null : feeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.cycle
     *
     * @return the value of rms_voiceverify_rate.cycle
     *
     * @mbggenerated
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.cycle
     *
     * @param cycle the value for rms_voiceverify_rate.cycle
     *
     * @mbggenerated
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per
     *
     * @return the value of rms_voiceverify_rate.per
     *
     * @mbggenerated
     */
    public BigDecimal getPer() {
        if(per != null){
            return per.setScale(4);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per
     *
     * @param per the value for rms_voiceverify_rate.per
     *
     * @mbggenerated
     */
    public void setPer(BigDecimal per) {
        this.per = per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per_discount
     *
     * @return the value of rms_voiceverify_rate.per_discount
     *
     * @mbggenerated
     */
    public Integer getPerDiscount() {
        return perDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per_discount
     *
     * @param perDiscount the value for rms_voiceverify_rate.per_discount
     *
     * @mbggenerated
     */
    public void setPerDiscount(Integer perDiscount) {
        this.perDiscount = perDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per6
     *
     * @return the value of rms_voiceverify_rate.per6
     *
     * @mbggenerated
     */
    public BigDecimal getPer6() {
        if(per6 != null){
            return per6.setScale(4);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per6
     *
     * @param per6 the value for rms_voiceverify_rate.per6
     *
     * @mbggenerated
     */
    public void setPer6(BigDecimal per6) {
        this.per6 = per6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per6_discount
     *
     * @return the value of rms_voiceverify_rate.per6_discount
     *
     * @mbggenerated
     */
    public Integer getPer6Discount() {
        return per6Discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per6_discount
     *
     * @param per6Discount the value for rms_voiceverify_rate.per6_discount
     *
     * @mbggenerated
     */
    public void setPer6Discount(Integer per6Discount) {
        this.per6Discount = per6Discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per60
     *
     * @return the value of rms_voiceverify_rate.per60
     *
     * @mbggenerated
     */
    public BigDecimal getPer60() {
        if(per60 != null){
            return per60.setScale(4);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per60
     *
     * @param per60 the value for rms_voiceverify_rate.per60
     *
     * @mbggenerated
     */
    public void setPer60(BigDecimal per60) {
        this.per60 = per60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.per60_discount
     *
     * @return the value of rms_voiceverify_rate.per60_discount
     *
     * @mbggenerated
     */
    public Integer getPer60Discount() {
        return per60Discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.per60_discount
     *
     * @param per60Discount the value for rms_voiceverify_rate.per60_discount
     *
     * @mbggenerated
     */
    public void setPer60Discount(Integer per60Discount) {
        this.per60Discount = per60Discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.perx
     *
     * @return the value of rms_voiceverify_rate.perx
     *
     * @mbggenerated
     */
    public BigDecimal getPerx() {
        return perx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.perx
     *
     * @param perx the value for rms_voiceverify_rate.perx
     *
     * @mbggenerated
     */
    public void setPerx(BigDecimal perx) {
        this.perx = perx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.recording
     *
     * @return the value of rms_voiceverify_rate.recording
     *
     * @mbggenerated
     */
    public BigDecimal getRecording() {
        if(recording != null){
            return recording.setScale(4);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.recording
     *
     * @param recording the value for rms_voiceverify_rate.recording
     *
     * @mbggenerated
     */
    public void setRecording(BigDecimal recording) {
        this.recording = recording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.recording_discount
     *
     * @return the value of rms_voiceverify_rate.recording_discount
     *
     * @mbggenerated
     */
    public Integer getRecordingDiscount() {
        return recordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.recording_discount
     *
     * @param recordingDiscount the value for rms_voiceverify_rate.recording_discount
     *
     * @mbggenerated
     */
    public void setRecordingDiscount(Integer recordingDiscount) {
        this.recordingDiscount = recordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_voiceverify_rate.addtime
     *
     * @return the value of rms_voiceverify_rate.addtime
     *
     * @mbggenerated
     */
    public String getAddtime() {
        if(addtime != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            return dateFormat.format(addtime);
        }
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_voiceverify_rate.addtime
     *
     * @param addtime the value for rms_voiceverify_rate.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}