package com.e9cloud.mybatis.domain;

import java.util.Date;

public class BusinessType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_type.sid
     *
     * @mbggenerated
     */

    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_type.bus_type
     *
     * @mbggenerated
     */
    private String busType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_type.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business_type.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_type.id
     *
     * @return the value of tb_business_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_type.id
     *
     * @param id the value for tb_business_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_type.sid
     *
     * @return the value of tb_business_type.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_type.sid
     *
     * @param sid the value for tb_business_type.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_type.bus_type
     *
     * @return the value of tb_business_type.bus_type
     *
     * @mbggenerated
     */
    public String getBusType() {
        return busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_type.bus_type
     *
     * @param busType the value for tb_business_type.bus_type
     *
     * @mbggenerated
     */
    public void setBusType(String busType) {
        this.busType = busType == null ? null : busType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_type.status
     *
     * @return the value of tb_business_type.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_type.status
     *
     * @param status the value for tb_business_type.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business_type.create_date
     *
     * @return the value of tb_business_type.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business_type.create_date
     *
     * @param createDate the value for tb_business_type.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}