package com.e9cloud.mybatis.domain;

import java.util.Date;

public class CodeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_type.bus_name
     *
     * @mbggenerated
     */
    private String busName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_type.bus_type
     *
     * @mbggenerated
     */
    private String busType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_type.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_type.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_type.id
     *
     * @return the value of tb_code_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_type.id
     *
     * @param id the value for tb_code_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_type.bus_name
     *
     * @return the value of tb_code_type.bus_name
     *
     * @mbggenerated
     */
    public String getBusName() {
        return busName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_type.bus_name
     *
     * @param busName the value for tb_code_type.bus_name
     *
     * @mbggenerated
     */
    public void setBusName(String busName) {
        this.busName = busName == null ? null : busName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_type.bus_type
     *
     * @return the value of tb_code_type.bus_type
     *
     * @mbggenerated
     */
    public String getBusType() {
        return busType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_type.bus_type
     *
     * @param busType the value for tb_code_type.bus_type
     *
     * @mbggenerated
     */
    public void setBusType(String busType) {
        this.busType = busType == null ? null : busType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_type.status
     *
     * @return the value of tb_code_type.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_type.status
     *
     * @param status the value for tb_code_type.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_type.create_date
     *
     * @return the value of tb_code_type.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_type.create_date
     *
     * @param createDate the value for tb_code_type.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}