package com.e9cloud.mybatis.domain;

import java.util.Date;

public class ExtraType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_extra_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_extra_service.sid
     *
     * @mbggenerated
     */
    private String sid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_extra_service.extra_type
     *
     * @mbggenerated
     */
    private String extraType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_extra_service.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_extra_service.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_extra_service.id
     *
     * @return the value of tb_extra_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_extra_service.id
     *
     * @param id the value for tb_extra_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_extra_service.sid
     *
     * @return the value of tb_extra_service.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_extra_service.sid
     *
     * @param sid the value for tb_extra_service.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_extra_service.extra_type
     *
     * @return the value of tb_extra_service.extra_type
     *
     * @mbggenerated
     */
    public String getExtraType() {
        return extraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_extra_service.extra_type
     *
     * @param extraType the value for tb_extra_service.extra_type
     *
     * @mbggenerated
     */
    public void setExtraType(String extraType) {
        this.extraType = extraType == null ? null : extraType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_extra_service.status
     *
     * @return the value of tb_extra_service.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_extra_service.status
     *
     * @param status the value for tb_extra_service.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_extra_service.create_date
     *
     * @return the value of tb_extra_service.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_extra_service.create_date
     *
     * @param createDate the value for tb_extra_service.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}