package com.e9cloud.mybatis.domain;

public class RelayBusinessZero {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.relay_id
     *
     * @mbggenerated
     */
    private Integer relayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.direction
     *
     * @mbggenerated
     */
    private Byte direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.opertion
     *
     * @mbggenerated
     */
    private Byte opertion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.num_type
     *
     * @mbggenerated
     */
    private Byte numType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_zero.operator
     *
     * @mbggenerated
     */
    private Integer operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.id
     *
     * @return the value of tb_relay_business_zero.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.id
     *
     * @param id the value for tb_relay_business_zero.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.relay_id
     *
     * @return the value of tb_relay_business_zero.relay_id
     *
     * @mbggenerated
     */
    public Integer getRelayId() {
        return relayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.relay_id
     *
     * @param relayId the value for tb_relay_business_zero.relay_id
     *
     * @mbggenerated
     */
    public void setRelayId(Integer relayId) {
        this.relayId = relayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.direction
     *
     * @return the value of tb_relay_business_zero.direction
     *
     * @mbggenerated
     */
    public Byte getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.direction
     *
     * @param direction the value for tb_relay_business_zero.direction
     *
     * @mbggenerated
     */
    public void setDirection(Byte direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.opertion
     *
     * @return the value of tb_relay_business_zero.opertion
     *
     * @mbggenerated
     */
    public Byte getOpertion() {
        return opertion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.opertion
     *
     * @param opertion the value for tb_relay_business_zero.opertion
     *
     * @mbggenerated
     */
    public void setOpertion(Byte opertion) {
        this.opertion = opertion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.num_type
     *
     * @return the value of tb_relay_business_zero.num_type
     *
     * @mbggenerated
     */
    public Byte getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.num_type
     *
     * @param numType the value for tb_relay_business_zero.num_type
     *
     * @mbggenerated
     */
    public void setNumType(Byte numType) {
        this.numType = numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_zero.operator
     *
     * @return the value of tb_relay_business_zero.operator
     *
     * @mbggenerated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_zero.operator
     *
     * @param operator the value for tb_relay_business_zero.operator
     *
     * @mbggenerated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }
}