package com.e9cloud.mybatis.domain;

import java.util.Date;

public class RelayNumPool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_numpool.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_numpool.relay_num
     *
     * @mbggenerated
     */
    private String relayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_numpool.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_numpool.max_concurrent
     *
     * @mbggenerated
     */
    private Integer maxConcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_numpool.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_numpool.id
     *
     * @return the value of tb_relay_numpool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_numpool.id
     *
     * @param id the value for tb_relay_numpool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_numpool.relay_num
     *
     * @return the value of tb_relay_numpool.relay_num
     *
     * @mbggenerated
     */
    public String getRelayNum() {
        return relayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_numpool.relay_num
     *
     * @param relayNum the value for tb_relay_numpool.relay_num
     *
     * @mbggenerated
     */
    public void setRelayNum(String relayNum) {
        this.relayNum = relayNum == null ? null : relayNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_numpool.number
     *
     * @return the value of tb_relay_numpool.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_numpool.number
     *
     * @param number the value for tb_relay_numpool.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_numpool.max_concurrent
     *
     * @return the value of tb_relay_numpool.max_concurrent
     *
     * @mbggenerated
     */
    public Integer getMaxConcurrent() {
        return maxConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_numpool.max_concurrent
     *
     * @param maxConcurrent the value for tb_relay_numpool.max_concurrent
     *
     * @mbggenerated
     */
    public void setMaxConcurrent(Integer maxConcurrent) {
        this.maxConcurrent = maxConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_numpool.create_time
     *
     * @return the value of tb_relay_numpool.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_numpool.create_time
     *
     * @param createTime the value for tb_relay_numpool.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}