package com.e9cloud.mybatis.domain;

public class RelayBusinessAreaCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.relay_id
     *
     * @mbggenerated
     */
    private Integer relayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.direction
     *
     * @mbggenerated
     */
    private Byte direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.opertion
     *
     * @mbggenerated
     */
    private Byte opertion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.type_num
     *
     * @mbggenerated
     */
    private Byte numType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relay_business_area_code.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.id
     *
     * @return the value of tb_relay_business_area_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.id
     *
     * @param id the value for tb_relay_business_area_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.relay_id
     *
     * @return the value of tb_relay_business_area_code.relay_id
     *
     * @mbggenerated
     */
    public Integer getRelayId() {
        return relayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.relay_id
     *
     * @param relayId the value for tb_relay_business_area_code.relay_id
     *
     * @mbggenerated
     */
    public void setRelayId(Integer relayId) {
        this.relayId = relayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.direction
     *
     * @return the value of tb_relay_business_area_code.direction
     *
     * @mbggenerated
     */
    public Byte getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.direction
     *
     * @param direction the value for tb_relay_business_area_code.direction
     *
     * @mbggenerated
     */
    public void setDirection(Byte direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.opertion
     *
     * @return the value of tb_relay_business_area_code.opertion
     *
     * @mbggenerated
     */
    public Byte getOpertion() {
        return opertion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.opertion
     *
     * @param opertion the value for tb_relay_business_area_code.opertion
     *
     * @mbggenerated
     */
    public void setOpertion(Byte opertion) {
        this.opertion = opertion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.type_num
     *
     * @return the value of tb_relay_business_area_code.type_num
     *
     * @mbggenerated
     */
    public Byte getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.type_num
     *
     * @param numType the value for tb_relay_business_area_code.type_num
     *
     * @mbggenerated
     */
    public void setNumType(Byte numType) {
        this.numType = numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relay_business_area_code.content
     *
     * @return the value of tb_relay_business_area_code.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relay_business_area_code.content
     *
     * @param content the value for tb_relay_business_area_code.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}