package com.e9cloud.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class SecretVoice implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.voice_size
     *
     * @mbggenerated
     */
    private String voiceSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.voice_name
     *
     * @mbggenerated
     */
    private String voiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.voice_url
     *
     * @mbggenerated
     */
    private String voiceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.common
     *
     * @mbggenerated
     */
    private String common;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_secret_voice.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.id
     *
     * @return the value of tb_secret_voice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.id
     *
     * @param id the value for tb_secret_voice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.appid
     *
     * @return the value of tb_secret_voice.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.appid
     *
     * @param appid the value for tb_secret_voice.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.voice_size
     *
     * @return the value of tb_secret_voice.voice_size
     *
     * @mbggenerated
     */
    public String getVoiceSize() {
        return voiceSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.voice_size
     *
     * @param voiceSize the value for tb_secret_voice.voice_size
     *
     * @mbggenerated
     */
    public void setVoiceSize(String voiceSize) {
        this.voiceSize = voiceSize == null ? null : voiceSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.voice_name
     *
     * @return the value of tb_secret_voice.voice_name
     *
     * @mbggenerated
     */
    public String getVoiceName() {
        return voiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.voice_name
     *
     * @param voiceName the value for tb_secret_voice.voice_name
     *
     * @mbggenerated
     */
    public void setVoiceName(String voiceName) {
        this.voiceName = voiceName == null ? null : voiceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.voice_url
     *
     * @return the value of tb_secret_voice.voice_url
     *
     * @mbggenerated
     */
    public String getVoiceUrl() {
        return voiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.voice_url
     *
     * @param voiceUrl the value for tb_secret_voice.voice_url
     *
     * @mbggenerated
     */
    public void setVoiceUrl(String voiceUrl) {
        this.voiceUrl = voiceUrl == null ? null : voiceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.status
     *
     * @return the value of tb_secret_voice.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.status
     *
     * @param status the value for tb_secret_voice.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.common
     *
     * @return the value of tb_secret_voice.common
     *
     * @mbggenerated
     */
    public String getCommon() {
        return common;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.common
     *
     * @param common the value for tb_secret_voice.common
     *
     * @mbggenerated
     */
    public void setCommon(String common) {
        this.common = common == null ? null : common.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.create_date
     *
     * @return the value of tb_secret_voice.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.create_date
     *
     * @param createDate the value for tb_secret_voice.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_secret_voice.update_date
     *
     * @return the value of tb_secret_voice.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_secret_voice.update_date
     *
     * @param updateDate the value for tb_secret_voice.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}