package com.e9cloud.mybatis.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

public class SipphonRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.feeid
     *
     * @mbggenerated
     */
    private String feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.appid
     *
     * @mbggenerated
     */

    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.start_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.end_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.forever
     *
     * @mbggenerated
     */
    private Boolean forever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_a
     *
     * @mbggenerated
     */
    private BigDecimal restA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_a_discount
     *
     * @mbggenerated
     */
    private Short restADiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_a_cycle
     *
     * @mbggenerated
     */
    private Short restACycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b
     *
     * @mbggenerated
     */
    private BigDecimal restB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b_discount
     *
     * @mbggenerated
     */
    private Short restBDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b_cycle
     *
     * @mbggenerated
     */
    private Short restBCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b_sipphone
     *
     * @mbggenerated
     */
    private BigDecimal restBSipphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b_sipphone_discount
     *
     * @mbggenerated
     */
    private Short restBSipphoneDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_b_sipphone_cycle
     *
     * @mbggenerated
     */
    private Short restBSipphoneCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_recording
     *
     * @mbggenerated
     */
    private BigDecimal restRecording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_recording_discount
     *
     * @mbggenerated
     */
    private Short restRecordingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.rest_recording_cycle
     *
     * @mbggenerated
     */
    private Short restRecordingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall
     *
     * @mbggenerated
     */
    private BigDecimal sipcall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall_discount
     *
     * @mbggenerated
     */
    private Short sipcallDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall_cycle
     *
     * @mbggenerated
     */
    private Short sipcallCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcallsip
     *
     * @mbggenerated
     */
    private BigDecimal sipcallsip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcallsip_discount
     *
     * @mbggenerated
     */
    private Short sipcallsipDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcallsip_cycle
     *
     * @mbggenerated
     */
    private Short sipcallsipCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall_recording
     *
     * @mbggenerated
     */
    private BigDecimal sipcallRecording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall_recording_discount
     *
     * @mbggenerated
     */
    private Short sipcallRecordingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.sipcall_recording_cycle
     *
     * @mbggenerated
     */
    private Short sipcallRecordingCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall
     *
     * @mbggenerated
     */
    private BigDecimal backcall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall_discount
     *
     * @mbggenerated
     */
    private Short backcallDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall_cycle
     *
     * @mbggenerated
     */
    private Short backcallCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall_recording
     *
     * @mbggenerated
     */
    private BigDecimal backcallRecording;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall_recording_discount
     *
     * @mbggenerated
     */
    private Short backcallRecordingDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.backcall_recording_cycle
     *
     * @mbggenerated
     */
    private Short backcallRecordingCycle;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.num_rent
     *
     * @mbggenerated
     */
    private BigDecimal numRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.num_rent_discount
     *
     * @mbggenerated
     */
    private Integer numRentDiscount;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.num_min_cost
     *
     * @mbggenerated
     */
    private BigDecimal numMinCost;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rms_sipphone_rate.ctime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date ctime;


    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date ctime1;

    private UserAdmin userAdmin;
    private AuthenCompany authenCompany;


    public String getCtime() {
        if(ctime != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            return dateFormat.format(ctime);
        }
        return null;
    }
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }


    public String getCtime1() {
        if(ctime1 != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            return dateFormat.format(ctime1);
        }
        return null;
    }

    public void setCtime1(Date ctime1) {
        this.ctime1 = ctime1;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.feeid
     *
     * @return the value of rms_sipphone_rate.feeid
     *
     * @mbggenerated
     */
    public String getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.feeid
     *
     * @param feeid the value for rms_sipphone_rate.feeid
     *
     * @mbggenerated
     */
    public void setFeeid(String feeid) {
        this.feeid = feeid == null ? null : feeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.appid
     *
     * @return the value of rms_sipphone_rate.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.appid
     *
     * @param appid the value for rms_sipphone_rate.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.start_date
     *
     * @return the value of rms_sipphone_rate.start_date
     *
     * @mbggenerated
     */
    public String getStartDate() {
        if(startDate != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            return dateFormat.format(startDate);
        }
        return null;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        if(endDate != null){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            return dateFormat.format(endDate);
        }
        return null;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.forever
     *
     * @return the value of rms_sipphone_rate.forever
     *
     * @mbggenerated
     */
    public Boolean getForever() {
        return forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.forever
     *
     * @param forever the value for rms_sipphone_rate.forever
     *
     * @mbggenerated
     */
    public void setForever(Boolean forever) {
        this.forever = forever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_a
     *
     * @return the value of rms_sipphone_rate.rest_a
     *
     * @mbggenerated
     */
    public BigDecimal getRestA() {
        return restA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_a
     *
     * @param restA the value for rms_sipphone_rate.rest_a
     *
     * @mbggenerated
     */
    public void setRestA(BigDecimal restA) {
        this.restA = restA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_a_discount
     *
     * @return the value of rms_sipphone_rate.rest_a_discount
     *
     * @mbggenerated
     */
    public Short getRestADiscount() {
        return restADiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_a_discount
     *
     * @param restADiscount the value for rms_sipphone_rate.rest_a_discount
     *
     * @mbggenerated
     */
    public void setRestADiscount(Short restADiscount) {
        this.restADiscount = restADiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_a_cycle
     *
     * @return the value of rms_sipphone_rate.rest_a_cycle
     *
     * @mbggenerated
     */
    public Short getRestACycle() {
        return restACycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_a_cycle
     *
     * @param restACycle the value for rms_sipphone_rate.rest_a_cycle
     *
     * @mbggenerated
     */
    public void setRestACycle(Short restACycle) {
        this.restACycle = restACycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b
     *
     * @return the value of rms_sipphone_rate.rest_b
     *
     * @mbggenerated
     */
    public BigDecimal getRestB() {
        return restB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b
     *
     * @param restB the value for rms_sipphone_rate.rest_b
     *
     * @mbggenerated
     */
    public void setRestB(BigDecimal restB) {
        this.restB = restB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b_discount
     *
     * @return the value of rms_sipphone_rate.rest_b_discount
     *
     * @mbggenerated
     */
    public Short getRestBDiscount() {
        return restBDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b_discount
     *
     * @param restBDiscount the value for rms_sipphone_rate.rest_b_discount
     *
     * @mbggenerated
     */
    public void setRestBDiscount(Short restBDiscount) {
        this.restBDiscount = restBDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b_cycle
     *
     * @return the value of rms_sipphone_rate.rest_b_cycle
     *
     * @mbggenerated
     */
    public Short getRestBCycle() {
        return restBCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b_cycle
     *
     * @param restBCycle the value for rms_sipphone_rate.rest_b_cycle
     *
     * @mbggenerated
     */
    public void setRestBCycle(Short restBCycle) {
        this.restBCycle = restBCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b_sipphone
     *
     * @return the value of rms_sipphone_rate.rest_b_sipphone
     *
     * @mbggenerated
     */
    public BigDecimal getRestBSipphone() {
        return restBSipphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b_sipphone
     *
     * @param restBSipphone the value for rms_sipphone_rate.rest_b_sipphone
     *
     * @mbggenerated
     */
    public void setRestBSipphone(BigDecimal restBSipphone) {
        this.restBSipphone = restBSipphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b_sipphone_discount
     *
     * @return the value of rms_sipphone_rate.rest_b_sipphone_discount
     *
     * @mbggenerated
     */
    public Short getRestBSipphoneDiscount() {
        return restBSipphoneDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b_sipphone_discount
     *
     * @param restBSipphoneDiscount the value for rms_sipphone_rate.rest_b_sipphone_discount
     *
     * @mbggenerated
     */
    public void setRestBSipphoneDiscount(Short restBSipphoneDiscount) {
        this.restBSipphoneDiscount = restBSipphoneDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_b_sipphone_cycle
     *
     * @return the value of rms_sipphone_rate.rest_b_sipphone_cycle
     *
     * @mbggenerated
     */
    public Short getRestBSipphoneCycle() {
        return restBSipphoneCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_b_sipphone_cycle
     *
     * @param restBSipphoneCycle the value for rms_sipphone_rate.rest_b_sipphone_cycle
     *
     * @mbggenerated
     */
    public void setRestBSipphoneCycle(Short restBSipphoneCycle) {
        this.restBSipphoneCycle = restBSipphoneCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_recording
     *
     * @return the value of rms_sipphone_rate.rest_recording
     *
     * @mbggenerated
     */
    public BigDecimal getRestRecording() {
        return restRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_recording
     *
     * @param restRecording the value for rms_sipphone_rate.rest_recording
     *
     * @mbggenerated
     */
    public void setRestRecording(BigDecimal restRecording) {
        this.restRecording = restRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_recording_discount
     *
     * @return the value of rms_sipphone_rate.rest_recording_discount
     *
     * @mbggenerated
     */
    public Short getRestRecordingDiscount() {
        return restRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_recording_discount
     *
     * @param restRecordingDiscount the value for rms_sipphone_rate.rest_recording_discount
     *
     * @mbggenerated
     */
    public void setRestRecordingDiscount(Short restRecordingDiscount) {
        this.restRecordingDiscount = restRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.rest_recording_cycle
     *
     * @return the value of rms_sipphone_rate.rest_recording_cycle
     *
     * @mbggenerated
     */
    public Short getRestRecordingCycle() {
        return restRecordingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.rest_recording_cycle
     *
     * @param restRecordingCycle the value for rms_sipphone_rate.rest_recording_cycle
     *
     * @mbggenerated
     */
    public void setRestRecordingCycle(Short restRecordingCycle) {
        this.restRecordingCycle = restRecordingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall
     *
     * @return the value of rms_sipphone_rate.sipcall
     *
     * @mbggenerated
     */
    public BigDecimal getSipcall() {
        return sipcall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall
     *
     * @param sipcall the value for rms_sipphone_rate.sipcall
     *
     * @mbggenerated
     */
    public void setSipcall(BigDecimal sipcall) {
        this.sipcall = sipcall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall_discount
     *
     * @return the value of rms_sipphone_rate.sipcall_discount
     *
     * @mbggenerated
     */
    public Short getSipcallDiscount() {
        return sipcallDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall_discount
     *
     * @param sipcallDiscount the value for rms_sipphone_rate.sipcall_discount
     *
     * @mbggenerated
     */
    public void setSipcallDiscount(Short sipcallDiscount) {
        this.sipcallDiscount = sipcallDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall_cycle
     *
     * @return the value of rms_sipphone_rate.sipcall_cycle
     *
     * @mbggenerated
     */
    public Short getSipcallCycle() {
        return sipcallCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall_cycle
     *
     * @param sipcallCycle the value for rms_sipphone_rate.sipcall_cycle
     *
     * @mbggenerated
     */
    public void setSipcallCycle(Short sipcallCycle) {
        this.sipcallCycle = sipcallCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcallsip
     *
     * @return the value of rms_sipphone_rate.sipcallsip
     *
     * @mbggenerated
     */
    public BigDecimal getSipcallsip() {
        return sipcallsip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcallsip
     *
     * @param sipcallsip the value for rms_sipphone_rate.sipcallsip
     *
     * @mbggenerated
     */
    public void setSipcallsip(BigDecimal sipcallsip) {
        this.sipcallsip = sipcallsip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcallsip_discount
     *
     * @return the value of rms_sipphone_rate.sipcallsip_discount
     *
     * @mbggenerated
     */
    public Short getSipcallsipDiscount() {
        return sipcallsipDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcallsip_discount
     *
     * @param sipcallsipDiscount the value for rms_sipphone_rate.sipcallsip_discount
     *
     * @mbggenerated
     */
    public void setSipcallsipDiscount(Short sipcallsipDiscount) {
        this.sipcallsipDiscount = sipcallsipDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcallsip_cycle
     *
     * @return the value of rms_sipphone_rate.sipcallsip_cycle
     *
     * @mbggenerated
     */
    public Short getSipcallsipCycle() {
        return sipcallsipCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcallsip_cycle
     *
     * @param sipcallsipCycle the value for rms_sipphone_rate.sipcallsip_cycle
     *
     * @mbggenerated
     */
    public void setSipcallsipCycle(Short sipcallsipCycle) {
        this.sipcallsipCycle = sipcallsipCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall_recording
     *
     * @return the value of rms_sipphone_rate.sipcall_recording
     *
     * @mbggenerated
     */
    public BigDecimal getSipcallRecording() {
        return sipcallRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall_recording
     *
     * @param sipcallRecording the value for rms_sipphone_rate.sipcall_recording
     *
     * @mbggenerated
     */
    public void setSipcallRecording(BigDecimal sipcallRecording) {
        this.sipcallRecording = sipcallRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall_recording_discount
     *
     * @return the value of rms_sipphone_rate.sipcall_recording_discount
     *
     * @mbggenerated
     */
    public Short getSipcallRecordingDiscount() {
        return sipcallRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall_recording_discount
     *
     * @param sipcallRecordingDiscount the value for rms_sipphone_rate.sipcall_recording_discount
     *
     * @mbggenerated
     */
    public void setSipcallRecordingDiscount(Short sipcallRecordingDiscount) {
        this.sipcallRecordingDiscount = sipcallRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.sipcall_recording_cycle
     *
     * @return the value of rms_sipphone_rate.sipcall_recording_cycle
     *
     * @mbggenerated
     */
    public Short getSipcallRecordingCycle() {
        return sipcallRecordingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.sipcall_recording_cycle
     *
     * @param sipcallRecordingCycle the value for rms_sipphone_rate.sipcall_recording_cycle
     *
     * @mbggenerated
     */
    public void setSipcallRecordingCycle(Short sipcallRecordingCycle) {
        this.sipcallRecordingCycle = sipcallRecordingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall
     *
     * @return the value of rms_sipphone_rate.backcall
     *
     * @mbggenerated
     */
    public BigDecimal getBackcall() {
        return backcall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall
     *
     * @param backcall the value for rms_sipphone_rate.backcall
     *
     * @mbggenerated
     */
    public void setBackcall(BigDecimal backcall) {
        this.backcall = backcall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall_discount
     *
     * @return the value of rms_sipphone_rate.backcall_discount
     *
     * @mbggenerated
     */
    public Short getBackcallDiscount() {
        return backcallDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall_discount
     *
     * @param backcallDiscount the value for rms_sipphone_rate.backcall_discount
     *
     * @mbggenerated
     */
    public void setBackcallDiscount(Short backcallDiscount) {
        this.backcallDiscount = backcallDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall_cycle
     *
     * @return the value of rms_sipphone_rate.backcall_cycle
     *
     * @mbggenerated
     */
    public Short getBackcallCycle() {
        return backcallCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall_cycle
     *
     * @param backcallCycle the value for rms_sipphone_rate.backcall_cycle
     *
     * @mbggenerated
     */
    public void setBackcallCycle(Short backcallCycle) {
        this.backcallCycle = backcallCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall_recording
     *
     * @return the value of rms_sipphone_rate.backcall_recording
     *
     * @mbggenerated
     */
    public BigDecimal getBackcallRecording() {
        return backcallRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall_recording
     *
     * @param backcallRecording the value for rms_sipphone_rate.backcall_recording
     *
     * @mbggenerated
     */
    public void setBackcallRecording(BigDecimal backcallRecording) {
        this.backcallRecording = backcallRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall_recording_discount
     *
     * @return the value of rms_sipphone_rate.backcall_recording_discount
     *
     * @mbggenerated
     */
    public Short getBackcallRecordingDiscount() {
        return backcallRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall_recording_discount
     *
     * @param backcallRecordingDiscount the value for rms_sipphone_rate.backcall_recording_discount
     *
     * @mbggenerated
     */
    public void setBackcallRecordingDiscount(Short backcallRecordingDiscount) {
        this.backcallRecordingDiscount = backcallRecordingDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.backcall_recording_cycle
     *
     * @return the value of rms_sipphone_rate.backcall_recording_cycle
     *
     * @mbggenerated
     */
    public Short getBackcallRecordingCycle() {
        return backcallRecordingCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rms_sipphone_rate.backcall_recording_cycle
     *
     * @param backcallRecordingCycle the value for rms_sipphone_rate.backcall_recording_cycle
     *
     * @mbggenerated
     */
    public void setBackcallRecordingCycle(Short backcallRecordingCycle) {
        this.backcallRecordingCycle = backcallRecordingCycle;
    }

    public BigDecimal getNumRent() {
        return numRent;
    }

    public void setNumRent(BigDecimal numRent) {
        this.numRent = numRent;
    }

    public Integer getNumRentDiscount() {
        return numRentDiscount;
    }

    public void setNumRentDiscount(Integer numRentDiscount) {
        this.numRentDiscount = numRentDiscount;
    }

    public BigDecimal getNumMinCost() {
        return numMinCost;
    }

    public void setNumMinCost(BigDecimal numMinCost) {
        this.numMinCost = numMinCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rms_sipphone_rate.ctime
     *
     * @return the value of rms_sipphone_rate.ctime
     *
     * @mbggenerated
     */


    public Date getEndDate1() {
        return endDate1;
    }

    public void setEndDate1(Date endDate1) {
        this.endDate1 = endDate1;
    }

    public UserAdmin getUserAdmin() {
        return userAdmin;
    }

    public void setUserAdmin(UserAdmin userAdmin) {
        this.userAdmin = userAdmin;
    }

    public AuthenCompany getAuthenCompany() {
        return authenCompany;
    }

    public void setAuthenCompany(AuthenCompany authenCompany) {
        this.authenCompany = authenCompany;
    }
}