package com.e9cloud.mybatis.domain;

import java.util.Date;

public class SubApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.subid
     *
     * @mbggenerated
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.sub_name
     *
     * @mbggenerated
     */
    private String subName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.sub_pwd
     *
     * @mbggenerated
     */
    private String subPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sub_app.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.subid
     *
     * @return the value of tb_sub_app.subid
     *
     * @mbggenerated
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.subid
     *
     * @param subid the value for tb_sub_app.subid
     *
     * @mbggenerated
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.appid
     *
     * @return the value of tb_sub_app.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.appid
     *
     * @param appid the value for tb_sub_app.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.sub_name
     *
     * @return the value of tb_sub_app.sub_name
     *
     * @mbggenerated
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.sub_name
     *
     * @param subName the value for tb_sub_app.sub_name
     *
     * @mbggenerated
     */
    public void setSubName(String subName) {
        this.subName = subName == null ? null : subName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.sub_pwd
     *
     * @return the value of tb_sub_app.sub_pwd
     *
     * @mbggenerated
     */
    public String getSubPwd() {
        return subPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.sub_pwd
     *
     * @param subPwd the value for tb_sub_app.sub_pwd
     *
     * @mbggenerated
     */
    public void setSubPwd(String subPwd) {
        this.subPwd = subPwd == null ? null : subPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.status
     *
     * @return the value of tb_sub_app.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.status
     *
     * @param status the value for tb_sub_app.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sub_app.create_date
     *
     * @return the value of tb_sub_app.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sub_app.create_date
     *
     * @param createDate the value for tb_sub_app.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}