package com.e9cloud.mybatis.domain;

import java.util.Date;

public class UserExternInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_type1
     *
     * @mbggenerated
     */
    private Integer attenType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_way1
     *
     * @mbggenerated
     */
    private String attenWay1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_type2
     *
     * @mbggenerated
     */
    private Integer attenType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_way2
     *
     * @mbggenerated
     */
    private String attenWay2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_type3
     *
     * @mbggenerated
     */
    private Integer attenType3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.atten_way3
     *
     * @mbggenerated
     */
    private String attenWay3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_admin_externinfo.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    private String responsiblePerson;

    public String getResponsiblePerson() {
        return responsiblePerson;
    }

    public void setResponsiblePerson(String responsiblePerson) {
        this.responsiblePerson = responsiblePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.id
     *
     * @return the value of tb_user_admin_externinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.id
     *
     * @param id the value for tb_user_admin_externinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.uid
     *
     * @return the value of tb_user_admin_externinfo.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.uid
     *
     * @param uid the value for tb_user_admin_externinfo.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.qq
     *
     * @return the value of tb_user_admin_externinfo.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.qq
     *
     * @param qq the value for tb_user_admin_externinfo.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.weixin
     *
     * @return the value of tb_user_admin_externinfo.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.weixin
     *
     * @param weixin the value for tb_user_admin_externinfo.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.address
     *
     * @return the value of tb_user_admin_externinfo.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.address
     *
     * @param address the value for tb_user_admin_externinfo.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_type1
     *
     * @return the value of tb_user_admin_externinfo.atten_type1
     *
     * @mbggenerated
     */
    public Integer getAttenType1() {
        return attenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_type1
     *
     * @param attenType1 the value for tb_user_admin_externinfo.atten_type1
     *
     * @mbggenerated
     */
    public void setAttenType1(Integer attenType1) {
        this.attenType1 = attenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_way1
     *
     * @return the value of tb_user_admin_externinfo.atten_way1
     *
     * @mbggenerated
     */
    public String getAttenWay1() {
        return attenWay1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_way1
     *
     * @param attenWay1 the value for tb_user_admin_externinfo.atten_way1
     *
     * @mbggenerated
     */
    public void setAttenWay1(String attenWay1) {
        this.attenWay1 = attenWay1 == null ? null : attenWay1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_type2
     *
     * @return the value of tb_user_admin_externinfo.atten_type2
     *
     * @mbggenerated
     */
    public Integer getAttenType2() {
        return attenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_type2
     *
     * @param attenType2 the value for tb_user_admin_externinfo.atten_type2
     *
     * @mbggenerated
     */
    public void setAttenType2(Integer attenType2) {
        this.attenType2 = attenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_way2
     *
     * @return the value of tb_user_admin_externinfo.atten_way2
     *
     * @mbggenerated
     */
    public String getAttenWay2() {
        return attenWay2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_way2
     *
     * @param attenWay2 the value for tb_user_admin_externinfo.atten_way2
     *
     * @mbggenerated
     */
    public void setAttenWay2(String attenWay2) {
        this.attenWay2 = attenWay2 == null ? null : attenWay2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_type3
     *
     * @return the value of tb_user_admin_externinfo.atten_type3
     *
     * @mbggenerated
     */
    public Integer getAttenType3() {
        return attenType3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_type3
     *
     * @param attenType3 the value for tb_user_admin_externinfo.atten_type3
     *
     * @mbggenerated
     */
    public void setAttenType3(Integer attenType3) {
        this.attenType3 = attenType3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.atten_way3
     *
     * @return the value of tb_user_admin_externinfo.atten_way3
     *
     * @mbggenerated
     */
    public String getAttenWay3() {
        return attenWay3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.atten_way3
     *
     * @param attenWay3 the value for tb_user_admin_externinfo.atten_way3
     *
     * @mbggenerated
     */
    public void setAttenWay3(String attenWay3) {
        this.attenWay3 = attenWay3 == null ? null : attenWay3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.create_date
     *
     * @return the value of tb_user_admin_externinfo.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.create_date
     *
     * @param createDate the value for tb_user_admin_externinfo.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_admin_externinfo.update_date
     *
     * @return the value of tb_user_admin_externinfo.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_admin_externinfo.update_date
     *
     * @param updateDate the value for tb_user_admin_externinfo.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}