package com.e9cloud.mybatis.domain;

import java.util.Date;

public class VoiceVerify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.appid
     *
     * @mbggenerated
     */
    private String appid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.play_num
     *
     * @mbggenerated
     */
    private Byte playNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.called_max
     *
     * @mbggenerated
     */
    private Byte calledMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.audit_status
     *
     * @mbggenerated
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.audit_common
     *
     * @mbggenerated
     */
    private String auditCommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.v_url
     *
     * @mbggenerated
     */
    private String vUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.v_size
     *
     * @mbggenerated
     */
    private String vSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.t_content
     *
     * @mbggenerated
     */
    private String tContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.atime
     *
     * @mbggenerated
     */
    private Date atime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_temp.v_path
     *
     * @mbggenerated
     */
    private String vPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.id
     *
     * @return the value of tb_voiceverify_temp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.id
     *
     * @param id the value for tb_voiceverify_temp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.appid
     *
     * @return the value of tb_voiceverify_temp.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.appid
     *
     * @param appid the value for tb_voiceverify_temp.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.name
     *
     * @return the value of tb_voiceverify_temp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.name
     *
     * @param name the value for tb_voiceverify_temp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.type
     *
     * @return the value of tb_voiceverify_temp.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.type
     *
     * @param type the value for tb_voiceverify_temp.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.language
     *
     * @return the value of tb_voiceverify_temp.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.language
     *
     * @param language the value for tb_voiceverify_temp.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.play_num
     *
     * @return the value of tb_voiceverify_temp.play_num
     *
     * @mbggenerated
     */
    public Byte getPlayNum() {
        return playNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.play_num
     *
     * @param playNum the value for tb_voiceverify_temp.play_num
     *
     * @mbggenerated
     */
    public void setPlayNum(Byte playNum) {
        this.playNum = playNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.called_max
     *
     * @return the value of tb_voiceverify_temp.called_max
     *
     * @mbggenerated
     */
    public Byte getCalledMax() {
        return calledMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.called_max
     *
     * @param calledMax the value for tb_voiceverify_temp.called_max
     *
     * @mbggenerated
     */
    public void setCalledMax(Byte calledMax) {
        this.calledMax = calledMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.audit_status
     *
     * @return the value of tb_voiceverify_temp.audit_status
     *
     * @mbggenerated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.audit_status
     *
     * @param auditStatus the value for tb_voiceverify_temp.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.audit_common
     *
     * @return the value of tb_voiceverify_temp.audit_common
     *
     * @mbggenerated
     */
    public String getAuditCommon() {
        return auditCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.audit_common
     *
     * @param auditCommon the value for tb_voiceverify_temp.audit_common
     *
     * @mbggenerated
     */
    public void setAuditCommon(String auditCommon) {
        this.auditCommon = auditCommon == null ? null : auditCommon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.audit_time
     *
     * @return the value of tb_voiceverify_temp.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.audit_time
     *
     * @param auditTime the value for tb_voiceverify_temp.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.v_url
     *
     * @return the value of tb_voiceverify_temp.v_url
     *
     * @mbggenerated
     */
    public String getvUrl() {
        return vUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.v_url
     *
     * @param vUrl the value for tb_voiceverify_temp.v_url
     *
     * @mbggenerated
     */
    public void setvUrl(String vUrl) {
        this.vUrl = vUrl == null ? null : vUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.v_size
     *
     * @return the value of tb_voiceverify_temp.v_size
     *
     * @mbggenerated
     */
    public String getvSize() {
        return vSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.v_size
     *
     * @param vSize the value for tb_voiceverify_temp.v_size
     *
     * @mbggenerated
     */
    public void setvSize(String vSize) {
        this.vSize = vSize == null ? null : vSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.t_content
     *
     * @return the value of tb_voiceverify_temp.t_content
     *
     * @mbggenerated
     */
    public String gettContent() {
        return tContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.t_content
     *
     * @param tContent the value for tb_voiceverify_temp.t_content
     *
     * @mbggenerated
     */
    public void settContent(String tContent) {
        this.tContent = tContent == null ? null : tContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.atime
     *
     * @return the value of tb_voiceverify_temp.atime
     *
     * @mbggenerated
     */
    public Date getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.atime
     *
     * @param atime the value for tb_voiceverify_temp.atime
     *
     * @mbggenerated
     */
    public void setAtime(Date atime) {
        this.atime = atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.status
     *
     * @return the value of tb_voiceverify_temp.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.status
     *
     * @param status the value for tb_voiceverify_temp.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_temp.v_path
     *
     * @return the value of tb_voiceverify_temp.v_path
     *
     * @mbggenerated
     */
    public String getvPath() {
        return vPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_temp.v_path
     *
     * @param vPath the value for tb_voiceverify_temp.v_path
     *
     * @mbggenerated
     */
    public void setvPath(String vPath) {
        this.vPath = vPath;
    }
}