package com.e9cloud.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class VoiceVerifyApp implements Serializable {

    private static final long serialVersionUID = -2257936141473913973L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_app_pool.id
     *
     * @mbggenerated
     */
    private String id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_app_pool.uid
     *
     * @mbggenerated
     */
    private String uid;

    //用户名称
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_app_pool.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_app_pool.appid
     *
     * @mbggenerated
     */
    private String appid;

    //应用名称
    private String appName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_voiceverify_app_pool.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_app_pool.id
     *
     * @return the value of tb_voiceverify_app_pool.id
     *
     * @mbggenerated
     */


    public VoiceVerifyApp(){

    }

    public VoiceVerifyApp(String  appid){
        this.appid = appid == null ? null : appid.trim();
    }



    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }


    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_app_pool.id
     *
     * @param id the value for tb_voiceverify_app_pool.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_app_pool.uid
     *
     * @return the value of tb_voiceverify_app_pool.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_app_pool.uid
     *
     * @param uid the value for tb_voiceverify_app_pool.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_app_pool.sid
     *
     * @return the value of tb_voiceverify_app_pool.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_app_pool.sid
     *
     * @param sid the value for tb_voiceverify_app_pool.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_app_pool.appid
     *
     * @return the value of tb_voiceverify_app_pool.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_app_pool.appid
     *
     * @param appid the value for tb_voiceverify_app_pool.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_voiceverify_app_pool.addtime
     *
     * @return the value of tb_voiceverify_app_pool.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_voiceverify_app_pool.addtime
     *
     * @param addtime the value for tb_voiceverify_app_pool.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}